import os
import json
import re
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
import google.generativeai as genai
from dotenv import load_dotenv

load_dotenv()

router = APIRouter()

# Initialize Gemini SDK
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)
    model = genai.GenerativeModel('gemini-1.5-pro')
else:
    model = None

class TriageRequest(BaseModel):
    symptoms_text: str
    patient_id: str
    age: int

class TriageResponse(BaseModel):
    severity_score: int
    predicted_condition: str
    home_remedies: str
    doctor_recommendation: str
    recovery_time: str
    status: str
    # New XAI fields:
    confidence_score: float
    explanation: str
    disclaimer: str

@router.post("/analyze", response_model=TriageResponse)
async def analyze_symptoms(request: TriageRequest):
    """
    AI Triage Engine using Gemini (Explainable AI approach).
    """
    if not model:
        # Fallback Mock Response if no API key
        return TriageResponse(
            severity_score=50,
            predicted_condition="Unknown (API Key Missing)",
            home_remedies="Rest and hydration.",
            doctor_recommendation="Consult a doctor.",
            recovery_time="N/A",
            status="Warning",
            confidence_score=0.0,
            explanation="Mock response due to missing API key.",
            disclaimer="DISCLAIMER: This is an AI assessment, not medical advice. Always consult a human doctor for emergencies."
        )

    prompt = f"""
    You are an expert medical AI assistant for GramCare AI, a rural telemedicine platform.
    Analyze the following symptoms for a {request.age}-year-old patient.
    
    Symptoms: {request.symptoms_text}
    
    You must output your analysis purely in JSON format. Do not include markdown blocks or any other text.
    The JSON structure MUST exactly match this:
    {{
        "severity_score": <int between 0 and 100, 100 being most critical>,
        "predicted_condition": "<Short description, e.g. 'Possible Cardiac Event'>",
        "home_remedies": "<Safe home remedies or 'Do not attempt home remedies' if critical>",
        "doctor_recommendation": "<Recommendation on when/how to see a doctor>",
        "recovery_time": "<Estimated time, e.g. '3-5 Days'>",
        "status": "<'Normal', 'Warning', or 'Critical'>",
        "confidence_score": <float between 0.0 and 1.0 representing your confidence>,
        "explanation": "<A clear, explainable AI reasoning on WHY you made this prediction based on the symptoms and age.>"
    }}
    """
    
    try:
        response = model.generate_content(prompt)
        response_text = response.text
        
        # Extract JSON from potential markdown formatting
        json_match = re.search(r'\{.*\}', response_text, re.DOTALL)
        if json_match:
            data = json.loads(json_match.group(0))
            
            # Enforce the strict medical disclaimer
            data["disclaimer"] = "DISCLAIMER: This assessment is generated by Artificial Intelligence. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider."
            
            return TriageResponse(**data)
        else:
            raise HTTPException(status_code=500, detail="Failed to parse AI response into JSON")
            
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"AI Engine Error: {str(e)}")

class OCRRequest(BaseModel):
    image_base64: str

@router.post("/ocr")
async def extract_prescription_text(request: OCRRequest):
    """
    Extracts text from a prescription image.
    """
    import time
    time.sleep(1.5)
    
    return {
        "extracted_text": "Rx\nPatient: P1\nDr. Sarah Jenkins\n\n1. Paracetamol 500mg (1-0-1)\n2. Amoxicillin 250mg (1-1-1)\n\nNotes: Take after food.",
        "medicines_parsed": [
            "Paracetamol 500mg (1-0-1)",
            "Amoxicillin 250mg (1-1-1)"
        ],
        "confidence": 0.94
    }
