import os
import json
import re
import logging
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger("gramcare.ai_triage")

router = APIRouter()

# ============================================================
# Initialize Google Gemini SDK (new unified google-genai package)
# ============================================================
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
gemini_client = None

if GEMINI_API_KEY:
    try:
        from google import genai
        gemini_client = genai.Client(api_key=GEMINI_API_KEY)
        logger.info("Gemini AI client initialized successfully.")
    except Exception as e:
        logger.warning("Failed to initialize Gemini client: %s", str(e))
        gemini_client = None
else:
    logger.warning("GEMINI_API_KEY not set. AI Triage will return mock responses.")


# ============================================================
# Request / Response Models
# ============================================================
class TriageRequest(BaseModel):
    symptoms_text: str = Field(..., min_length=3, max_length=2000, description="Patient's symptom description")
    patient_id: str = Field(..., min_length=1, description="Patient identifier")
    age: int = Field(..., ge=0, le=150, description="Patient age")


class TriageResponse(BaseModel):
    severity_score: int = Field(..., ge=0, le=100)
    predicted_condition: str
    home_remedies: str
    doctor_recommendation: str
    recovery_time: str
    status: str
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    explanation: str
    disclaimer: str


# ============================================================
# AI Triage Endpoint
# ============================================================
MEDICAL_DISCLAIMER = (
    "DISCLAIMER: This assessment is generated by Artificial Intelligence. "
    "It is NOT a substitute for professional medical advice, diagnosis, or treatment. "
    "Always consult a qualified healthcare provider."
)

TRIAGE_PROMPT_TEMPLATE = """
You are an expert medical AI assistant for GramCare AI, a rural telemedicine platform in India.
Analyze the following symptoms for a {age}-year-old patient.

Symptoms: {symptoms}

MULTI-LANGUAGE INSTRUCTION:
The symptoms may be spoken or typed in a regional language (like Tamil, Hindi) or in English.
1. Auto-detect the language of the symptoms.
2. Analyze the medical condition deeply.
3. You must translate and write your final response (predicted_condition, home_remedies, doctor_recommendation, explanation) IN THE SAME LANGUAGE the user spoke in (or default to English if unclear).

You must output your analysis purely in JSON format. Do not include markdown blocks or any other text.
The JSON structure MUST exactly match this:
{{
    "severity_score": <int between 0 and 100, 100 being most critical>,
    "predicted_condition": "<Short description in user's language>",
    "home_remedies": "<Safe home remedies in user's language>",
    "doctor_recommendation": "<Recommendation in user's language>",
    "recovery_time": "<Estimated time in user's language>",
    "status": "<'Normal', 'Warning', or 'Critical' in English>",
    "confidence_score": <float between 0.0 and 1.0 representing your confidence>,
    "explanation": "<A clear, explainable AI reasoning on WHY you made this prediction based on the symptoms and age, written in the user's language.>"
}}
"""


@router.post("/analyze", response_model=TriageResponse)
async def analyze_symptoms(request: TriageRequest):
    """
    AI Triage Engine using Google Gemini (Explainable AI approach).
    
    - Accepts symptoms in any language (English, Tamil, Hindi, etc.)
    - Returns severity score, predicted condition, home remedies, and doctor recommendation
    - Includes explainable AI reasoning and confidence score
    - Enforces strict medical disclaimer
    """
    if not gemini_client:
        # Fallback Mock Response if no API key
        logger.info("Returning mock triage response (no Gemini client).")
        return TriageResponse(
            severity_score=50,
            predicted_condition="Unknown (API Key Not Configured)",
            home_remedies="Rest and hydration.",
            doctor_recommendation="Consult a doctor for proper evaluation.",
            recovery_time="N/A",
            status="Warning",
            confidence_score=0.0,
            explanation="This is a mock response because the Gemini API key is not configured. "
                        "Please set GEMINI_API_KEY in the .env file for real AI analysis.",
            disclaimer=MEDICAL_DISCLAIMER,
        )

    prompt = TRIAGE_PROMPT_TEMPLATE.format(
        age=request.age,
        symptoms=request.symptoms_text,
    )

    try:
        response = gemini_client.models.generate_content(
            model="gemini-2.0-flash",
            contents=prompt,
        )
        response_text = response.text
        logger.info("Gemini response received for patient %s (%d chars).", request.patient_id, len(response_text))

        # Extract JSON from potential markdown formatting
        json_match = re.search(r'\{.*\}', response_text, re.DOTALL)
        if json_match:
            data = json.loads(json_match.group(0))

            # Enforce the strict medical disclaimer (never trust AI to include it correctly)
            data["disclaimer"] = MEDICAL_DISCLAIMER

            # Clamp values to valid ranges
            data["severity_score"] = max(0, min(100, int(data.get("severity_score", 50))))
            data["confidence_score"] = max(0.0, min(1.0, float(data.get("confidence_score", 0.5))))

            return TriageResponse(**data)
        else:
            logger.error("Failed to parse JSON from Gemini response: %s", response_text[:200])
            raise HTTPException(
                status_code=500,
                detail="AI Engine returned an unparseable response. Please try again.",
            )

    except HTTPException:
        raise
    except json.JSONDecodeError as e:
        logger.error("JSON decode error: %s", str(e))
        raise HTTPException(
            status_code=500,
            detail="AI Engine returned malformed JSON. Please try again.",
        )
    except Exception as e:
        logger.error("AI Engine error: %s", str(e))
        raise HTTPException(
            status_code=500,
            detail=f"AI Engine Error: {str(e)}",
        )


# ============================================================
# OCR Endpoint (Gemini Vision-based for production)
# ============================================================
class OCRRequest(BaseModel):
    image_base64: str = Field(..., min_length=10, description="Base64-encoded image of prescription")


class OCRResponse(BaseModel):
    extracted_text: str
    medicines_parsed: list[str]
    confidence: float = Field(..., ge=0.0, le=1.0)


OCR_PROMPT = """
You are a medical prescription OCR system for GramCare AI.
Analyze this prescription image and extract:
1. The full text visible on the prescription.
2. A list of medicines with their dosages.

Respond in JSON format only, no markdown:
{
    "extracted_text": "<full visible text from the prescription>",
    "medicines_parsed": ["<Medicine 1 with dosage>", "<Medicine 2 with dosage>"],
    "confidence": <float 0.0 to 1.0>
}
"""


@router.post("/ocr", response_model=OCRResponse)
async def extract_prescription_text(request: OCRRequest):
    """
    Extracts text from a prescription image using Gemini Vision.
    Falls back to mock data if Gemini client is unavailable.
    """
    if not gemini_client:
        # Mock fallback for development without API key
        logger.info("Returning mock OCR response (no Gemini client).")
        return OCRResponse(
            extracted_text=(
                "Rx\nPatient: P1\nDr. Sarah Jenkins\n\n"
                "1. Paracetamol 500mg (1-0-1)\n"
                "2. Amoxicillin 250mg (1-1-1)\n\n"
                "Notes: Take after food."
            ),
            medicines_parsed=[
                "Paracetamol 500mg (1-0-1)",
                "Amoxicillin 250mg (1-1-1)",
            ],
            confidence=0.0,
        )

    try:
        import base64

        # Decode the base64 image
        image_bytes = base64.b64decode(request.image_base64)

        # Use Gemini Vision to analyze the prescription image
        response = gemini_client.models.generate_content(
            model="gemini-2.0-flash",
            contents=[
                OCR_PROMPT,
                {"inline_data": {"mime_type": "image/jpeg", "data": request.image_base64}},
            ],
        )
        response_text = response.text

        json_match = re.search(r'\{.*\}', response_text, re.DOTALL)
        if json_match:
            data = json.loads(json_match.group(0))
            data["confidence"] = max(0.0, min(1.0, float(data.get("confidence", 0.8))))
            return OCRResponse(**data)
        else:
            raise HTTPException(status_code=500, detail="Failed to parse OCR response.")

    except HTTPException:
        raise
    except Exception as e:
        logger.error("OCR Error: %s", str(e))
        raise HTTPException(status_code=500, detail=f"OCR Engine Error: {str(e)}")
