import logging
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field
from dotenv import load_dotenv
from sqlalchemy.orm import Session

import models
from ai import AITask, get_ai_manager
from core.ratelimit import rate_limit
from core.cloudinary_service import cloudinary_client
from database import get_db
from modules.auth.router import get_current_user_optional

load_dotenv()

logger = logging.getLogger("gramcare.ai_triage")

router = APIRouter()

# All AI provider selection, health checking, retries, and fallback are
# handled by AIManager (apps/backend_service/ai/manager.py) — this module
# has no knowledge of which provider (Gemini, OpenAI, Groq, Anthropic, or
# Mock) actually serves a given request, and does not import any AI SDK
# directly. See ai/README expectations: no module outside ai/providers/*.py
# may `import google.genai`/`openai`/`groq`/`anthropic`.
ai_manager = get_ai_manager()


# ============================================================
# Request / Response Models
# ============================================================
class TriageRequest(BaseModel):
    symptoms_text: str = Field(..., min_length=3, max_length=2000, description="Patient's symptom description")
    patient_id: str = Field(..., min_length=1, description="Patient identifier ('GUEST' for anonymous use)")
    age: int = Field(..., ge=0, le=150, description="Patient age")
    family_profile_id: Optional[int] = Field(None, description="Family member this analysis is for")
    # Planning doc: text/voice input plus an OPTIONAL photo (e.g. a rash,
    # visible wound) that the AI factors into the same severity assessment
    # — distinct from /ocr, which reads a prescription's printed text.
    image_base64: Optional[str] = Field(None, description="Optional base64 photo of a visible symptom")


class TriageResponse(BaseModel):
    severity_score: int = Field(..., ge=0, le=100)
    predicted_condition: str
    home_remedies: str
    doctor_recommendation: str
    recovery_time: str
    status: str
    confidence_score: float = Field(..., ge=0.0, le=1.0)
    explanation: str
    # Planning-doc mandated detail fields ("அது எதனால காஸ் ஆயிருக்கலாம்,
    # ஃபர்ஸ்ட் எய்ட் என்ன, சைடு எஃபெக்ட்ஸ் என்ன, என்னென்ன ட்ரீட்மென்ட்,
    # இப்படியே இருந்தா என்ன ஆகும், எந்த ஸ்பெஷலிஸ்ட்").
    possible_causes: str = ""
    first_aid: str = ""
    side_effects: str = ""
    treatment_options: str = ""
    untreated_outcome: str = ""
    specialist_type: str = ""       # e.g. Dermatologist, Cardiologist, General Physician
    language_detected: str = ""
    disclaimer: str
    # Cloudinary URL of the submitted symptom photo, if one was provided and
    # storage is configured — None otherwise (never blocks the analysis).
    image_url: Optional[str] = None


# ============================================================
# AI Triage Endpoint
# ============================================================
MEDICAL_DISCLAIMER = (
    "DISCLAIMER: This assessment is generated by Artificial Intelligence. "
    "It is NOT a substitute for professional medical advice, diagnosis, or treatment. "
    "Always consult a qualified healthcare provider."
)

TRIAGE_PROMPT_TEMPLATE = """
You are an expert medical AI assistant for GramCare AI, a rural telemedicine platform in India.
Analyze the following symptoms for a {age}-year-old patient.

Symptoms: {symptoms}
{image_note}

MULTI-LANGUAGE INSTRUCTION:
The symptoms may be spoken or typed in a regional language (like Tamil, Hindi) or in English.
1. Auto-detect the language of the symptoms.
2. Analyze the medical condition deeply.
3. You must translate and write your final response (predicted_condition, home_remedies, doctor_recommendation, explanation) IN THE SAME LANGUAGE the user spoke in (or default to English if unclear).

You must output your analysis purely in JSON format. Do not include markdown blocks or any other text.
The JSON structure MUST exactly match this:
{{
    "severity_score": <int between 0 and 100, 100 being most critical>,
    "predicted_condition": "<Short description in user's language>",
    "home_remedies": "<Safe home remedies in user's language>",
    "doctor_recommendation": "<Recommendation in user's language>",
    "recovery_time": "<Estimated time in user's language>",
    "status": "<'Normal', 'Warning', or 'Critical' in English>",
    "confidence_score": <float between 0.0 and 1.0 representing your confidence>,
    "explanation": "<A clear, explainable AI reasoning on WHY you made this prediction based on the symptoms and age, written in the user's language.>",
    "possible_causes": "<Likely causes, in user's language>",
    "first_aid": "<Immediate first-aid steps until reaching care, in user's language. NEVER include medicine dosages.>",
    "side_effects": "<What accompanying symptoms/complications to watch for, in user's language>",
    "treatment_options": "<Typical treatment approaches a doctor may consider, in user's language, phrased as information not instruction>",
    "untreated_outcome": "<What may happen if ignored, in user's language, factual not alarmist>",
    "specialist_type": "<The single most relevant specialist in English, e.g. 'Dermatologist', 'Cardiologist', 'General Physician'>",
    "language_detected": "<BCP-47 code of the user's language, e.g. 'ta', 'hi', 'en'>"
}}
"""


def _persist_triage_log(
    db: Session,
    request: TriageRequest,
    user: Optional[models.User],
    data: dict,
    image_url: Optional[str] = None,
) -> None:
    """Persist every analysis to TriageLog — the data backbone for the AI
    Doctor Assistant and Community Health Intelligence (planning doc). The
    model previously existed but was never written to. Failures here must
    never break the user-facing analysis, hence the guard."""
    try:
        db.add(
            models.TriageLog(
                patient_id=user.id if user else None,
                family_profile_id=request.family_profile_id if user else None,
                symptoms_text=request.symptoms_text,
                ai_severity_score=int(data.get("severity_score", 0)),
                ai_predicted_condition=str(data.get("predicted_condition", ""))[:250],
                ai_confidence=float(data.get("confidence_score", 0.0)),
                ai_explanation=str(data.get("explanation", "")),
                language_detected=data.get("language_detected"),
                image_url=image_url,
            )
        )
        db.commit()
    except Exception as e:  # pragma: no cover - defensive
        db.rollback()
        logger.error("Failed to persist triage log: %s", str(e))


async def run_triage_analysis(
    db: Session,
    user: Optional[models.User],
    symptoms_text: str,
    age: int,
    family_profile_id: Optional[int] = None,
    image_base64: Optional[str] = None,
) -> TriageResponse:
    """Core AI triage logic, shared by the public POST /triage/analyze
    endpoint below and the CHW proxy endpoint
    (modules/chw/router.py's POST /chw/patients/{patient_id}/triage) that
    runs triage on behalf of a CHW-registered patient.

    `user` is whoever the analysis should be ATTRIBUTED to (i.e. whose
    TriageLog row this becomes) — for the CHW proxy that is the patient
    themself, never the CHW who triggered the call, so a walk-in patient's
    triage history reads exactly like one they ran themselves.
    """
    image_b64 = None
    image_url = None
    if image_base64:
        try:
            import base64
            image_b64 = image_base64
            base64.b64decode(image_b64)
        except Exception:
            raise HTTPException(status_code=400, detail="Invalid Base64 image provided.")

        # Persist the original symptom photo (previously analyzed once and
        # discarded) so it's retrievable later — e.g. a doctor confirming
        # what the AI actually saw. Best-effort: never blocks the analysis.
        uploaded = cloudinary_client.upload_base64(image_b64, folder="gramcare/symptom_photos")
        if uploaded:
            image_url = uploaded["url"]

    prompt = TRIAGE_PROMPT_TEMPLATE.format(
        age=age,
        symptoms=symptoms_text,
        image_note=(
            "A photo of the visible symptom (e.g. rash, wound, swelling) is "
            "attached — factor what you see in it into severity_score, "
            "predicted_condition, and explanation."
            if image_b64 else ""
        ),
    )

    # AIManager guarantees a result (falling all the way back to
    # MockProvider internally) — this call cannot raise for "AI is down".
    # Passing image_base64 only when actually provided keeps plain
    # text/voice triage routable to every configured provider, including
    # non-vision ones (Groq) — see AIManager._candidates_for.
    outcome = await ai_manager.run(AITask.TRIAGE, prompt=prompt, image_base64=image_b64)
    data = dict(outcome.data)

    try:
        data["disclaimer"] = MEDICAL_DISCLAIMER
        data["severity_score"] = max(0, min(100, int(data.get("severity_score", 50))))
        data["confidence_score"] = max(0.0, min(1.0, float(data.get("confidence_score", 0.5))))

        result = TriageResponse(**data)
    except Exception as e:
        # The provider (or mock) returned a dict that doesn't validate
        # against TriageResponse — should be rare since MockProvider always
        # matches the schema exactly, but guard against a misbehaving real
        # provider response slipping through provider-level normalization.
        logger.error(
            "request_id=%s Failed to parse AI response into TriageResponse: %s",
            outcome.request_id, str(e),
        )
        result = TriageResponse(
            severity_score=50,
            predicted_condition="Unknown (invalid AI response)",
            home_remedies="Rest and hydration.",
            doctor_recommendation="Consult a doctor for proper evaluation.",
            recovery_time="N/A",
            status="Warning",
            confidence_score=0.0,
            explanation="The AI response could not be validated. Falling back to safe defaults.",
            possible_causes="Not available in fallback mode.",
            first_aid="Keep the patient comfortable and hydrated.",
            side_effects="",
            treatment_options="",
            untreated_outcome="",
            specialist_type="General Physician",
            language_detected="en",
            disclaimer=MEDICAL_DISCLAIMER,
        )

    result.image_url = image_url
    _persist_triage_log(
        db,
        TriageRequest(
            symptoms_text=symptoms_text,
            patient_id=str(user.id) if user else "GUEST",
            age=age,
            family_profile_id=family_profile_id,
        ),
        user,
        result.model_dump(),
        image_url=image_url,
    )
    return result


@router.post(
    "/analyze",
    response_model=TriageResponse,
    # Public (guest symptom checker) but rate-limited: this endpoint spends
    # real Gemini quota per call and previously had no abuse protection.
    dependencies=[Depends(rate_limit("triage", 20, 300))],
)
async def analyze_symptoms(
    request: TriageRequest,
    db: Session = Depends(get_db),
    current_user: Optional[models.User] = Depends(get_current_user_optional),
):
    """
    AI Triage Engine, routed entirely through AIManager (Gemini -> OpenAI ->
    Groq -> Anthropic -> Mock, in configured priority order — see
    ai/config.py). This function no longer knows which provider ends up
    serving the request.

    - Accepts symptoms in any language (English, Tamil, Hindi, etc.)
    - Returns severity score, predicted condition, home remedies, and doctor recommendation
    - Includes explainable AI reasoning and confidence score
    - Enforces strict medical disclaimer
    - Persists every analysis to TriageLog (attributed when authenticated)
    """
    return await run_triage_analysis(
        db,
        current_user,
        request.symptoms_text,
        request.age,
        family_profile_id=request.family_profile_id,
        image_base64=request.image_base64,
    )


# ============================================================
# OCR Endpoint (Gemini Vision-based for production)
# ============================================================
class OCRRequest(BaseModel):
    image_base64: str = Field(..., min_length=10, description="Base64-encoded image of prescription")


class OCRResponse(BaseModel):
    extracted_text: str
    medicines_parsed: list[str]
    confidence: float = Field(..., ge=0.0, le=1.0)
    # Cloudinary URL of the scanned image, if storage is configured. This
    # single endpoint backs the patient app's prescription scanner AND the
    # pharmacy dashboard's invoice scanner — both photos were previously
    # discarded immediately after OCR ran; now both are retrievable.
    image_url: Optional[str] = None


OCR_PROMPT = """
You are a medical prescription OCR system for GramCare AI.
Analyze this prescription image and extract:
1. The full text visible on the prescription.
2. A list of medicines with their dosages.

Respond in JSON format only, no markdown:
{
    "extracted_text": "<full visible text from the prescription>",
    "medicines_parsed": ["<Medicine 1 with dosage>", "<Medicine 2 with dosage>"],
    "confidence": <float 0.0 to 1.0>
}
"""


@router.post(
    "/ocr",
    response_model=OCRResponse,
    # Gemini Vision costs more per call than text triage — tighter window.
    dependencies=[Depends(rate_limit("ocr", 10, 300))],
)
async def extract_prescription_text(request: OCRRequest):
    """
    Extracts text from a prescription image. Routed through AIManager,
    which restricts OCR's candidate providers to ones that actually support
    vision (Gemini, OpenAI, ... -> Mock) regardless of configuration —
    see AIManager._candidates_for.
    """
    try:
        import base64
        base64.b64decode(request.image_base64)
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid Base64 Image provided to OCR.")

    # Best-effort: never blocks OCR if storage is unconfigured/unreachable.
    uploaded = cloudinary_client.upload_base64(request.image_base64, folder="gramcare/ocr_scans")
    image_url = uploaded["url"] if uploaded else None

    outcome = await ai_manager.run(AITask.OCR, prompt=OCR_PROMPT, image_base64=request.image_base64)
    data = dict(outcome.data)

    try:
        data["confidence"] = max(0.0, min(1.0, float(data.get("confidence", 0.8))))
        result = OCRResponse(**data)
    except Exception as e:
        logger.error("request_id=%s Failed to parse OCR response: %s", outcome.request_id, str(e))
        result = OCRResponse(
            extracted_text="[AI response could not be validated]",
            medicines_parsed=[],
            confidence=0.0,
        )
    result.image_url = image_url
    return result
