import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Lightweight English/Tamil localization — same approach as
/// apps/mobile_app's LocaleService (plain map instead of ARB codegen, so
/// `flutter analyze` stays clean on a fresh checkout with no generation
/// step). Doctors default to English (professional/clinical tool used
/// alongside the web portal), but many doctors in Tamil Nadu will prefer
/// Tamil, so the toggle is first-class exactly like the patient app.
class LocaleService extends ChangeNotifier {
  static const _key = 'gramcare_doctor_locale';
  String _code = 'en';

  String get code => _code;
  bool get isTamil => _code == 'ta';

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    _code = prefs.getString(_key) ?? 'en';
    notifyListeners();
  }

  Future<void> setCode(String code) async {
    _code = code;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_key, code);
    notifyListeners();
  }

  String t(String key) {
    final table = _code == 'ta' ? _ta : _en;
    return table[key] ?? _en[key] ?? key;
  }
}

const Map<String, String> _en = {
  'app_title': 'GramCare Doctor',
  'tagline': 'Consult, prescribe and review on the move',
  'login': 'Login',
  'username_hint': 'Username (e.g., doctor1)',
  'username_or_email_hint': 'Username or Email',
  'password_hint': 'Password',
  'invalid_credentials': 'Invalid credentials. Please try again.',
  'not_a_doctor_account': 'This account is not registered as a Doctor.',
  'login_failed': 'Login failed. Please check your connection and try again.',
  'dashboard': 'Dashboard',
  'appointment_queue': 'Appointment Queue',
  'no_appointments': 'No appointments in your queue right now.',
  'pull_to_refresh': 'Pull down to refresh',
  'status_pending': 'PENDING',
  'status_confirmed': 'CONFIRMED',
  'status_completed': 'COMPLETED',
  'status_cancelled': 'CANCELLED',
  'patient_detail': 'Patient Detail',
  'ai_pre_consult_summary': 'AI Pre-Consult Summary',
  'risk_flag': 'Risk',
  'active_medicines': 'Active Medicines',
  'recent_conditions': 'Recent AI Assessments',
  'latest_vitals': 'Latest Vitals',
  'medical_history': 'Medical History',
  'triage_summary': 'Triage Summary',
  'mark_confirmed': 'Mark Confirmed',
  'mark_completed': 'Mark Completed',
  'cancel_appointment': 'Cancel Appointment',
  'add_notes': 'Add Consultation Notes',
  'consultation_notes': 'Consultation Notes',
  'write_prescription': 'Write Prescription',
  'save_notes': 'Save Notes',
  'notes_saved': 'Consultation notes saved.',
  'no_history': 'No medical history records found.',
  'prescription_writer': 'Prescription Writer',
  'diagnosis': 'Diagnosis',
  'dosage_instructions': 'Dosage Instructions',
  'notes': 'Notes',
  'medicine_name': 'Medicine name',
  'dosage': 'Dosage',
  'frequency': 'Frequency',
  'duration': 'Duration',
  'add_medicine': 'Add medicine',
  'remove': 'Remove',
  'issue_prescription': 'Issue Prescription',
  'prescription_success': 'Prescription issued and synced to the patient\'s Health Wallet and pharmacy queue.',
  'prescription_failed': 'Failed to issue prescription. Please try again.',
  'at_least_one_medicine': 'Add at least one medicine before submitting.',
  'interaction_warning_title': 'Medicine Interaction Warning',
  'my_schedule': 'My Schedule',
  'availability_slots': 'Availability Slots',
  'add_slot': 'Add Slot',
  'start_time': 'Start time',
  'end_time': 'End time',
  'no_slots': 'No upcoming slots published yet.',
  'slot_booked': 'Booked',
  'slot_open': 'Open',
  'delete_slot_confirm': 'Delete this slot?',
  'available_for_consultation': 'Available for consultation',
  'critical_alerts': 'Critical Alerts',
  'no_active_alerts': 'No active emergency alerts right now.',
  'sos_severity': 'Severity',
  'sos_location': 'Location',
  'sos_status': 'Status',
  'refreshing': 'Refreshing…',
  'profile': 'Profile',
  'specialty': 'Specialty',
  'qualifications': 'Qualifications',
  'experience_years': 'Experience (years)',
  'consultation_fee': 'Consultation Fee',
  'languages': 'Languages',
  'logout': 'Logout',
  'language': 'Language',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'edit_profile': 'Edit Profile',
  'profile_updated': 'Profile updated.',
  'loading': 'Loading…',
  'error_generic': 'Something went wrong. Please try again.',
  'retry': 'Retry',
  'confirm': 'Confirm',
  'view_history': 'View Medical History',
  'status_pending_review': 'Pending Review',
  'status_approved': 'Approved',
  'status_not_approved': 'Not Approved',
  'application_under_review_title': 'Your application is under review',
  'application_under_review_body':
      'A government reviewer needs to verify your details before you can see appointments or patients. Complete your profile below, including your license document, to speed this up.',
  'application_rejected_title': 'Your application was not approved',
  'application_rejected_body': 'Update your details below and it will be reviewed again.',
  'rejection_reason': "Reviewer's reason",
  'license_number': 'Medical Registration / License Number',
  'license_number_hint': 'e.g. TN-MED-2026-00123',
  'service_hours': 'Service Hours',
  'service_hours_hint': 'e.g. Mon-Sat 9am-1pm',
  'change_photo': 'Change Photo',
  'license_document': 'License / ID Document',
  'license_document_note': 'Upload a clear photo or scan of your medical registration certificate.',
  'upload_document': 'Upload Document',
  'replace_document': 'Replace Document',
  'view_document': 'View uploaded document',
  'uploading': 'Uploading…',
  'photo_upload_failed': 'Photo upload failed.',
  'document_upload_failed': 'Document upload failed.',
  'document_uploaded': 'License document uploaded.',
  'go_to_profile': 'Go to My Profile',
  'video_consultation': 'Video Consultation',
  // Registration + forgot-password — previously this app had no
  // registration or password-recovery surface at all, only login.
  'forgot_password': 'Forgot password?',
  'new_doctor_register': 'New doctor? Create an account',
  'create_doctor_account': 'Create your doctor account',
  'create_doctor_account_subtitle': 'Registration needs phone verification and a government reviewer\'s approval before you can see appointments.',
  'full_name_hint': 'Full Name',
  'email_hint': 'Email',
  'password_hint_min8': 'Password (min 8 characters)',
  'phone_hint': 'Phone number',
  'phone_hint_optional': 'Phone number (optional)',
  'verify_phone_note': 'A verified phone number is required to register as a doctor.',
  'send_otp': 'Send OTP',
  'resend_otp': 'Resend OTP',
  'otp_hint': 'Enter OTP',
  'verify_otp': 'Verify',
  'enter_valid_phone': 'Enter a valid phone number.',
  'otp_send_failed': 'Could not send OTP. Check the number and try again.',
  'otp_incorrect': 'Incorrect OTP.',
  'verify_phone_first': 'Please verify your phone number before continuing.',
  'fill_required_fields': 'Please fill in all required fields.',
  'username_too_short': 'Username must be at least 3 characters.',
  'password_too_short': 'Password must be at least 8 characters.',
  'create_account': 'Create Account',
  'already_have_account': 'Already have an account? Sign in',
  'registration_check_email': "Account created. We've sent a verification link to your email — sign in once you've clicked it.",
  'registration_failed': 'Registration failed. Please check your details and try again.',
  'reset_password_title': 'Reset Password',
  'reset_password_tagline': "Enter your account email and we'll send you a reset link.",
  'send_reset_link': 'Send Reset Link',
  'reset_link_sent': "If that email is registered, we've sent a reset link to it. Check your inbox.",
  'reset_request_failed': 'Could not send the reset link. Please check your connection and try again.',
  'back_to_login': 'Back to Sign In',
  'enter_valid_email': 'Enter a valid email address.',
};

const Map<String, String> _ta = {
  'app_title': 'கிராம்கேர் டாக்டர்',
  'tagline': 'நகரும்போதே ஆலோசனை, மருந்துச்சீட்டு, பரிசோதனை',
  'login': 'உள்நுழைக',
  'username_hint': 'பயனர்பெயர் (எ.கா. doctor1)',
  'username_or_email_hint': 'பயனர்பெயர் அல்லது மின்னஞ்சல்',
  'password_hint': 'கடவுச்சொல்',
  'invalid_credentials': 'தவறான விவரங்கள். மீண்டும் முயற்சிக்கவும்.',
  'not_a_doctor_account': 'இந்தக் கணக்கு டாக்டர் கணக்காக பதிவு செய்யப்படவில்லை.',
  'login_failed': 'உள்நுழைவு தோல்வி. இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
  'dashboard': 'டாஷ்போர்டு',
  'appointment_queue': 'அப்பாயின்ட்மென்ட் வரிசை',
  'no_appointments': 'தற்போது உங்கள் வரிசையில் அப்பாயின்ட்மென்ட் இல்லை.',
  'pull_to_refresh': 'புதுப்பிக்க கீழே இழுக்கவும்',
  'status_pending': 'நிலுவையில்',
  'status_confirmed': 'உறுதி செய்யப்பட்டது',
  'status_completed': 'முடிந்தது',
  'status_cancelled': 'ரத்து செய்யப்பட்டது',
  'patient_detail': 'நோயாளி விவரம்',
  'ai_pre_consult_summary': 'AI முன்-ஆலோசனை சுருக்கம்',
  'risk_flag': 'ஆபத்து நிலை',
  'active_medicines': 'தற்போதைய மருந்துகள்',
  'recent_conditions': 'சமீபத்திய AI மதிப்பீடுகள்',
  'latest_vitals': 'சமீபத்திய உடல்நிலை அளவீடுகள்',
  'medical_history': 'மருத்துவ வரலாறு',
  'triage_summary': 'ட்ரையாஜ் சுருக்கம்',
  'mark_confirmed': 'உறுதி செய்யப்பட்டதாகக் குறிக்க',
  'mark_completed': 'முடிந்ததாகக் குறிக்க',
  'cancel_appointment': 'அப்பாயின்ட்மென்ட்டை ரத்து செய்',
  'add_notes': 'ஆலோசனை குறிப்புகளைச் சேர்க்க',
  'consultation_notes': 'ஆலோசனை குறிப்புகள்',
  'write_prescription': 'மருந்துச்சீட்டு எழுத',
  'save_notes': 'குறிப்புகளைச் சேமிக்க',
  'notes_saved': 'ஆலோசனை குறிப்புகள் சேமிக்கப்பட்டன.',
  'no_history': 'மருத்துவ வரலாறு பதிவுகள் இல்லை.',
  'prescription_writer': 'மருந்துச்சீட்டு எழுதுபவர்',
  'diagnosis': 'நோய் கண்டறிதல்',
  'dosage_instructions': 'மருந்து அளவு அறிவுறுத்தல்கள்',
  'notes': 'குறிப்புகள்',
  'medicine_name': 'மருந்தின் பெயர்',
  'dosage': 'அளவு',
  'frequency': 'எத்தனை முறை',
  'duration': 'கால அளவு',
  'add_medicine': 'மருந்து சேர்க்க',
  'remove': 'நீக்கு',
  'issue_prescription': 'மருந்துச்சீட்டு வழங்க',
  'prescription_success': 'மருந்துச்சீட்டு வழங்கப்பட்டு நோயாளியின் ஹெல்த் வாலட் மற்றும் மருந்தகக் வரிசையுடன் ஒத்திசைக்கப்பட்டது.',
  'prescription_failed': 'மருந்துச்சீட்டு வழங்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  'at_least_one_medicine': 'சமர்ப்பிக்கும் முன் குறைந்தது ஒரு மருந்தையாவது சேர்க்கவும்.',
  'interaction_warning_title': 'மருந்து எதிர்வினை எச்சரிக்கை',
  'my_schedule': 'எனது அட்டவணை',
  'availability_slots': 'கிடைக்கும் நேரங்கள்',
  'add_slot': 'நேரத்தைச் சேர்க்க',
  'start_time': 'தொடக்க நேரம்',
  'end_time': 'முடிவு நேரம்',
  'no_slots': 'இன்னும் நேரங்கள் வெளியிடப்படவில்லை.',
  'slot_booked': 'பதிவு செய்யப்பட்டது',
  'slot_open': 'திறந்துள்ளது',
  'delete_slot_confirm': 'இந்த நேரத்தை நீக்கவா?',
  'available_for_consultation': 'ஆலோசனைக்கு கிடைக்கிறேன்',
  'critical_alerts': 'அவசர எச்சரிக்கைகள்',
  'no_active_alerts': 'தற்போது செயலில் உள்ள அவசர எச்சரிக்கைகள் இல்லை.',
  'sos_severity': 'தீவிரம்',
  'sos_location': 'இடம்',
  'sos_status': 'நிலை',
  'refreshing': 'புதுப்பிக்கிறது…',
  'profile': 'சுயவிவரம்',
  'specialty': 'சிறப்பு பிரிவு',
  'qualifications': 'தகுதிகள்',
  'experience_years': 'அனுபவம் (ஆண்டுகள்)',
  'consultation_fee': 'ஆலோசனைக் கட்டணம்',
  'languages': 'மொழிகள்',
  'logout': 'வெளியேறு',
  'language': 'மொழி',
  'save': 'சேமிக்க',
  'cancel': 'ரத்து',
  'delete': 'நீக்கு',
  'edit_profile': 'சுயவிவரத்தைத் திருத்த',
  'profile_updated': 'சுயவிவரம் புதுப்பிக்கப்பட்டது.',
  'loading': 'ஏற்றுகிறது…',
  'error_generic': 'ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.',
  'retry': 'மீண்டும் முயற்சி',
  'confirm': 'உறுதிப்படுத்து',
  'view_history': 'மருத்துவ வரலாற்றைப் பார்க்க',
  'status_pending_review': 'மதிப்பாய்வில் உள்ளது',
  'status_approved': 'அங்கீகரிக்கப்பட்டது',
  'status_not_approved': 'அங்கீகரிக்கப்படவில்லை',
  'application_under_review_title': 'உங்கள் விண்ணப்பம் மதிப்பாய்வில் உள்ளது',
  'application_under_review_body':
      'அப்பாயின்ட்மென்ட்கள் அல்லது நோயாளிகளைப் பார்க்கும் முன் அரசு அதிகாரி உங்கள் விவரங்களைச் சரிபார்க்க வேண்டும். இதை விரைவுபடுத்த, கீழே உங்கள் சுயவிவரத்தை (உரிமத் ஆவணம் உட்பட) முழுமையாக்குங்கள்.',
  'application_rejected_title': 'உங்கள் விண்ணப்பம் அங்கீகரிக்கப்படவில்லை',
  'application_rejected_body': 'கீழே உங்கள் விவரங்களைப் புதுப்பிக்கவும், மீண்டும் மதிப்பாய்வு செய்யப்படும்.',
  'rejection_reason': 'மதிப்பாய்வாளரின் காரணம்',
  'license_number': 'மருத்துவப் பதிவு / உரிம எண்',
  'license_number_hint': 'எ.கா. TN-MED-2026-00123',
  'service_hours': 'சேவை நேரம்',
  'service_hours_hint': 'எ.கா. திங்கள்-சனி காலை 9 - மதியம் 1',
  'change_photo': 'புகைப்படத்தை மாற்ற',
  'license_document': 'உரிமம் / அடையாள ஆவணம்',
  'license_document_note': 'உங்கள் மருத்துவப் பதிவுச் சான்றிதழின் தெளிவான புகைப்படம் அல்லது ஸ்கேனைப் பதிவேற்றவும்.',
  'upload_document': 'ஆவணத்தைப் பதிவேற்ற',
  'replace_document': 'ஆவணத்தை மாற்ற',
  'view_document': 'பதிவேற்றிய ஆவணத்தைப் பார்க்க',
  'uploading': 'பதிவேற்றுகிறது…',
  'photo_upload_failed': 'புகைப்படப் பதிவேற்றம் தோல்வியடைந்தது.',
  'document_upload_failed': 'ஆவணப் பதிவேற்றம் தோல்வியடைந்தது.',
  'document_uploaded': 'உரிம ஆவணம் பதிவேற்றப்பட்டது.',
  'go_to_profile': 'எனது சுயவிவரத்திற்குச் செல்ல',
  'video_consultation': 'வீடியோ ஆலோசனை',
  'forgot_password': 'கடவுச்சொல் மறந்துவிட்டதா?',
  'new_doctor_register': 'புதிய டாக்டரா? கணக்கை உருவாக்க',
  'create_doctor_account': 'உங்கள் டாக்டர் கணக்கை உருவாக்கவும்',
  'create_doctor_account_subtitle': 'பதிவுக்கு தொலைபேசி சரிபார்ப்பும், அப்பாயின்ட்மென்ட்களைப் பார்க்க அரசு அதிகாரியின் ஒப்புதலும் தேவை.',
  'full_name_hint': 'முழுப் பெயர்',
  'email_hint': 'மின்னஞ்சல்',
  'password_hint_min8': 'கடவுச்சொல் (குறைந்தது 8 எழுத்துகள்)',
  'phone_hint': 'தொலைபேசி எண்',
  'phone_hint_optional': 'தொலைபேசி எண் (விருப்பத்திற்குரியது)',
  'verify_phone_note': 'டாக்டராகப் பதிவு செய்ய சரிபார்க்கப்பட்ட தொலைபேசி எண் தேவை.',
  'send_otp': 'OTP அனுப்பு',
  'resend_otp': 'மீண்டும் OTP அனுப்பு',
  'otp_hint': 'OTP-ஐ உள்ளிடவும்',
  'verify_otp': 'சரிபார்க்க',
  'enter_valid_phone': 'சரியான தொலைபேசி எண்ணை உள்ளிடவும்.',
  'otp_send_failed': 'OTP அனுப்ப முடியவில்லை. எண்ணைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
  'otp_incorrect': 'தவறான OTP.',
  'verify_phone_first': 'தொடர்வதற்கு முன் உங்கள் தொலைபேசி எண்ணைச் சரிபார்க்கவும்.',
  'fill_required_fields': 'தேவையான அனைத்து விவரங்களையும் நிரப்பவும்.',
  'username_too_short': 'பயனர்பெயர் குறைந்தது 3 எழுத்துகள் இருக்க வேண்டும்.',
  'password_too_short': 'கடவுச்சொல் குறைந்தது 8 எழுத்துகள் இருக்க வேண்டும்.',
  'create_account': 'கணக்கை உருவாக்கு',
  'already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக',
  'registration_check_email': 'கணக்கு உருவாக்கப்பட்டது. உங்கள் மின்னஞ்சலுக்கு சரிபார்ப்பு இணைப்பை அனுப்பியுள்ளோம் — அதைக் கிளிக் செய்த பிறகு உள்நுழையவும்.',
  'registration_failed': 'பதிவு தோல்வியடைந்தது. உங்கள் விவரங்களைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
  'reset_password_title': 'கடவுச்சொல்லை மீட்டமைக்க',
  'reset_password_tagline': 'உங்கள் கணக்கு மின்னஞ்சலை உள்ளிடவும், மீட்டமைப்பு இணைப்பை அனுப்புவோம்.',
  'send_reset_link': 'மீட்டமைப்பு இணைப்பை அனுப்பு',
  'reset_link_sent': 'அந்த மின்னஞ்சல் பதிவு செய்யப்பட்டிருந்தால், மீட்டமைப்பு இணைப்பை அனுப்பியுள்ளோம். உங்கள் இன்பாக்ஸைச் சரிபார்க்கவும்.',
  'reset_request_failed': 'மீட்டமைப்பு இணைப்பை அனுப்ப முடியவில்லை. இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
  'back_to_login': 'உள்நுழைவுக்குத் திரும்பு',
  'enter_valid_email': 'சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்.',
};
