import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Lightweight English/Tamil localization.
///
/// Why not flutter_localizations + ARB codegen: this repo's CI builds run
/// `flutter analyze` on a clean checkout, and gen-l10n output would need to
/// be committed or generated in CI. A plain map keeps localization fully
/// source-controlled, trivially testable, and lets rural-facing strings be
/// reviewed by Tamil speakers in one file. If the string count grows past a
/// few hundred, migrate to ARB (mechanical change — call sites keep the
/// same `S.of(context).key` shape via this provider).
///
/// Planning doc: "ரீஜினல் லாங்குவேஜ் வாய்ஸ் அண்ட் டெக்ஸ்ட் சப்போர்ட்
/// ரொம்பவே முக்கியம்" — Tamil is the launch language alongside English.
class LocaleService extends ChangeNotifier {
  static const _key = 'gramcare_locale';
  String _code = 'ta'; // Tamil-first: the target user is the rural patient

  String get code => _code;
  bool get isTamil => _code == 'ta';

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    _code = prefs.getString(_key) ?? 'ta';
    notifyListeners();
  }

  Future<void> setCode(String code) async {
    _code = code;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_key, code);
    notifyListeners();
  }

  String t(String key) {
    final table = _code == 'ta' ? _ta : _en;
    return table[key] ?? _en[key] ?? key;
  }
}

const Map<String, String> _en = {
  'app_title': 'GramCare AI',
  'tagline': 'Offline-First Healthcare Ecosystem',
  'back': 'Back',
  'medicine_recall_alert': 'Medicine Recall Alert',
  'login': 'Login',
  'username_hint': 'Username (e.g., patient1)',
  'username_or_email_hint': 'Username or Email',
  'password_hint': 'Password',
  'invalid_credentials': 'Invalid credentials. Please try again.',
  'forgot_password': 'Forgot password?',
  'new_patient_register': 'New to GramCare? Create an account',
  'create_account_title': 'Create your account',
  'create_account_subtitle': 'Free for patients — takes under a minute.',
  'full_name_hint': 'Full Name',
  'email_hint': 'Email',
  'phone_hint_optional': 'Phone (optional — for SMS reminders)',
  'password_hint_min8': 'Password (min 8 characters)',
  'create_account': 'Create Account',
  'already_have_account': 'Already have an account? Sign in',
  'fill_required_fields': 'Please fill in name, username, email and password.',
  'username_too_short': 'Username must be at least 3 characters.',
  'password_too_short': 'Password must be at least 8 characters.',
  'registration_failed': 'Registration failed. Please check your details and try again.',
  'reset_password_title': 'Reset your password',
  'reset_password_tagline': "Enter your account email and we'll send you a reset link.",
  'send_reset_link': 'Send Reset Link',
  'reset_link_sent': "If that email is registered, we've sent a reset link to it. Check your inbox.",
  'reset_request_failed': 'Could not send the reset link. Please check your connection and try again.',
  'back_to_login': 'Back to Sign In',
  'enter_valid_email': 'Enter a valid email address.',
  'acting_for_self': 'Acting for: Myself',
  'acting_for': 'Acting for',
  'myself': 'Myself',
  'my_own_health': 'My own health',
  'who_is_this_for': 'Who is this for?',
  'add_member': 'Add member',
  'health_wallet': 'Health Wallet',
  'symptom_checker': 'Symptom Checker',
  'scan_prescription': 'Scan Prescription',
  'find_medicine': 'Find Medicine',
  'iot_vitals': 'IoT Vitals',
  'medicine_reminders': 'Medicine Reminders',
  'emergency_sos': 'EMERGENCY SOS',
  'emergency_contacts': 'Emergency Contacts',
  'hold_to_sos': 'Hold the button for 3 seconds to send SOS',
  'hold_to_sos_listening': "Hold and speak — tell us what happened",
  'sos_sent': 'EMERGENCY SOS SENT — help has been alerted',
  'sos_failed': 'SOS FAILED TO SEND. Please call 108 directly.',
  'sos_sms_fallback': 'No internet — opening SMS to alert your contacts',
  'sos_status_active': 'Alert sent — waiting for a hospital to respond.',
  'sos_status_responded': 'Help is on the way. A hospital has responded to your alert.',
  'sos_status_resolved': 'This emergency has been marked resolved.',
  'sos_escalated': 'No response yet — your alert has been forwarded to the next nearest hospital.',
  'sos_status_error': 'Could not check your alert status. Retrying…',
  'open_in_maps': 'Open in Maps',
  'describe_symptoms': 'Describe your symptoms in detail:',
  'speak_symptoms': 'Tap the mic and speak',
  'add_symptom_photo': 'Add a photo of the symptom (optional)',
  'listening': 'Listening…',
  'analyze_with_ai': 'Analyze with AI',
  'analyzing': 'Analyzing…',
  'severity_score': 'Severity Score',
  'predicted_condition': 'Possible Condition',
  'doctor_recommendation': 'Doctor Recommendation',
  'home_remedies': 'Home Remedies',
  'first_aid': 'First Aid',
  'possible_causes': 'Possible Causes',
  'treatment_options': 'Treatment Options',
  'untreated_outcome': 'If Left Untreated',
  'specialist': 'Recommended Specialist',
  'recovery_time': 'Recovery Time',
  'side_effects': 'Side Effects to Watch For',
  'why_ai_thinks_this': 'Why does the AI think this?',
  'tap_to_hear': 'Tap to hear',
  'critical_prompt_title': 'This looks serious',
  'critical_prompt_body': 'The AI assessment is CRITICAL. Do you want to send an Emergency SOS now?',
  'send_sos_now': 'SEND SOS NOW',
  'not_now': 'Not now',
  'no_records': 'No records yet. Run a symptom check or scan a prescription.',
  'sync_now': 'Sync now',
  'save_to_wallet': 'Looks right — Save to Wallet',
  'retake_photo': 'Retake photo',
  'saved_to_wallet': 'Saved to Health Wallet — will sync when online',
  'camera': 'Camera',
  'gallery': 'Gallery',
  'search_failed': 'Search failed. Are you online?',
  'offline_estimate_banner': "Offline estimate — not a full AI analysis. This is only a basic keyword-based safety check because we couldn't reach the server. Connect to the internet when possible, and seek care immediately if this feels serious.",
  'offline_no_match': "You appear to be offline, and this couldn't produce even an offline estimate for these symptoms. If you're at all concerned, please seek care or call your local emergency number.",
  'in_stock': 'In stock',
  'not_available': 'Not available here',
  'alternatives': 'Same-effect alternatives',
  'language': 'Language',
  'name': 'Name',
  'phone': 'Phone',
  'relation': 'Relation',
  'save': 'Save',
  // Health Passport
  'health_passport': 'Health Passport',
  // Lab tests
  'lab_tests': 'Lab Tests',
  // Preventive care & referrals
  'preventive_care': 'Preventive Care',
  // My Care (AI Care Navigator)
  'my_care': 'My Care',
  'my_care_subtitle': 'What to do next, in order of importance — with the reason for each.',
  'my_care_none': 'Nothing needs your attention right now.',
  'my_care_load_failed': 'Could not load your care plan.',
  'open': 'Open',
  'priority_critical': 'CRITICAL',
  'priority_high': 'HIGH',
  'priority_medium': 'MEDIUM',
  'priority_low': 'LOW',
  'preventive_due_tab': 'Due now',
  'referrals_tab': 'Referrals',
  'preventive_none': 'No preventive checks suggested yet.',
  'preventive_due_now': 'Needs attention',
  'preventive_up_to_date': 'Up to date',
  'preventive_due_badge': 'DUE',
  'preventive_last_done': 'Last done',
  'preventive_book_test': 'Book this test',
  'preventive_book_consult': 'Book a consultation',
  'preventive_load_failed': 'Could not load your preventive care checks.',
  'referrals_load_failed': 'Could not load your referrals.',
  'referrals_none': 'No referrals yet. A doctor can refer you to a specialist.',
  'referral_status_pending': 'Pending',
  'referral_status_accepted': 'Accepted',
  'referral_status_declined': 'Declined',
  'referral_status_completed': 'Completed',
  'lab_book_tab': 'Book a test',
  'lab_my_bookings_tab': 'My bookings',
  'lab_search_hint': 'Search tests (blood sugar, thyroid...)',
  'lab_no_tests': 'No tests match your search.',
  'lab_no_bookings': 'No lab tests booked yet.',
  'lab_choose_center': 'Choose a lab centre',
  'lab_home_collection': 'Collect the sample at my home',
  'lab_confirm_booking': 'Confirm booking',
  'lab_booked': 'Test booked. The lab will update the status.',
  'lab_booking_failed': 'Could not book this test. Please try again.',
  'lab_tests_load_failed': 'Could not load the test catalog.',
  'lab_bookings_load_failed': 'Could not load your bookings.',
  'lab_centers_load_failed': 'Could not load lab centres.',
  'lab_no_centers': 'No lab centres are available yet.',
  'lab_report': 'Report',
  'lab_status_booked': 'Booked',
  'lab_status_sample_collected': 'Sample collected',
  'lab_status_processing': 'Processing',
  'lab_status_report_ready': 'Report ready',
  'lab_status_completed': 'Completed',
  'lab_status_cancelled': 'Cancelled',
  'passport_subtitle': 'Emergency details a paramedic or hospital can read from your phone, even without a GramCare account.',
  'blood_group': 'Blood group',
  'allergies': 'Allergies',
  'allergies_hint': 'e.g. Penicillin, peanuts',
  'chronic_conditions': 'Chronic conditions',
  'chronic_conditions_hint': 'e.g. Type 2 diabetes, asthma',
  'saving': 'Saving...',
  'passport_load_failed': 'Could not load your health passport.',
  'passport_saved': 'Health passport saved.',
  'passport_save_failed': 'Could not save your health passport.',
  'passport_qr_note': 'Show this code in an emergency. Scanning it opens your blood group, allergies and conditions — no login needed.',
  'passport_copy_link': 'Copy link',
  'passport_link_copied': 'Link copied.',
  'passport_new_code': 'New code',
  'passport_regenerate_confirm': 'Create a new QR code? The old one stops working — use this if your phone or a printed copy was lost.',
  'passport_new_code_done': 'New QR code created. The old one no longer works.',
  'passport_regenerate_failed': 'Could not create a new QR code.',
  'passport_save_for_qr': 'Save your details to generate an emergency QR code.',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'add_contact': 'Add contact',
  'no_contacts': 'Add family numbers to alert them during an emergency.',
  'offline_note': 'Offline — data will sync when connected',
  'add_family_member_title': 'Add family member',
  'relation_hint': 'Relation (e.g. Mother)',
  'age_hint': 'Age',
  'gender_female': 'Female',
  'gender_male': 'Male',
  'gender_other': 'Other',
  'could_not_save_member': 'Could not save member. Are you online?',
  'medicine_name_hint': 'Medicine name (e.g. Paracetamol)',
  'search_medicine_prompt': 'Search to see which pharmacy has your medicine.',
  'no_pharmacies_found': 'No pharmacies found.',
  'jan_aushadhi': 'Jan Aushadhi',
  'preorder_cta': 'Pre-order for when restocked',
  'preordered_notify': "Pre-ordered — we'll notify you",
  'preorder_failed': 'Could not place the pre-order. Please try again.',
  'health_vitals_title': 'Health Vitals',
  'heart_rate': 'Heart Rate',
  'spo2': 'SpO2',
  'sleep_deep': 'Sleep (deep)',
  'sleep_light': 'Sleep (light)',
  'steps_today': 'steps today',
  'daily_step_goal': 'Daily step goal',
  'heart_rate_trend': 'Heart Rate trend (bpm)',
  'spo2_trend': 'SpO2 trend (%)',
  'no_data_yet': 'No data yet',
  'sync_or_log_manually': 'Connect a device, or enter readings yourself:',
  'heart_rate_bpm': 'Heart Rate (bpm)',
  'spo2_percent': 'SpO2 (%)',
  'steps_today_label': 'Steps today',
  'deep_sleep_hrs': 'Deep sleep (hrs)',
  'light_sleep_hrs': 'Light sleep (hrs)',
  'save_vitals': 'Save Vitals',
  'invalid_vitals_range': 'Check the values: heart rate 1–299, SpO2 0–100, temperature 25–45 °C.',
  // Shown only when the shared AI quota is spent, offering the user
  // their own provider key rather than a dead assistant.
  'ai_limit_exhausted': 'AI limit reached',
  'have_own_api_key': 'Do you have your own API key?',
  'yes': 'Yes',
  'no': 'No',
  'paste_api_key': 'Paste your API key',
  'api_key_stays_on_phone': 'Stored only on this phone. Never sent to GramCare.',
  'save_and_retry': 'Save & retry',
  'ai_using_your_key': 'Using your API key',
  'remove_api_key': 'Remove key',
  'vitals_saved': 'Vitals recorded successfully.',
  'vitals_save_failed': 'Could not save vitals. Are you online?',
  'connect_ble_device': 'Connect a Bluetooth health device',
  'ble_profiles_note': 'Works with devices that support the standard Bluetooth heart rate, pulse oximeter or thermometer profile.',
  'ble_not_supported': "This phone doesn't support Bluetooth Low Energy.",
  'ble_turn_on': 'Turn on Bluetooth to connect a device.',
  'ble_choose_device': 'Choose a device',
  'ble_searching': 'Searching for health devices…',
  'ble_none_found': 'No health devices found. Make sure the device is switched on and close by.',
  'ble_scan_failed': 'Could not search for devices. Check Bluetooth permission and try again.',
  'ble_unnamed_device': 'Unnamed device',
  'ble_connecting': 'Connecting…',
  'ble_connect_failed': 'Could not connect to the device. Try again.',
  'ble_no_health_data': "This device doesn't provide standard health readings.",
  'ble_live_from': 'Live readings from',
  'ble_waiting_reading': 'Waiting for a reading — keep the device on your finger or skin.',
  'ble_disconnect': 'Disconnect',
  'ble_disconnected': 'Device disconnected.',
  'ble_search_again': 'Search again',
  'temperature': 'Temperature',
  'temperature_c': 'Temperature (°C)',
  'sleep_deep_light': 'Sleep (deep / light)',
  'vitals_need_one_value': 'Enter at least one reading.',
  'camera_open_failed': 'Could not open camera/gallery.',
  'ocr_read_failed': 'Could not read the prescription. Check your connection and try again.',
  'scan_for': 'Scan for',
  'ai_reading_prescription': 'AI is reading the prescription…',
  'ai_found_medicines': 'AI found these medicines:',
  'sure': 'sure',
  'no_medicines_recognized': 'No medicines recognized — check the photo quality.',
  'full_text': 'Full text:',
  'medicine_info_failed': 'Could not load medicine information. Are you online?',
  'what_its_for': "What it's for",
  'dosage_guidance': 'Dosage guidance',
  'side_effects_watch': 'Side effects to watch for',
  'precautions': 'Precautions',
  'book_consultation': 'Book Consultation',
  'my_appointments': 'My Appointments',
  'no_doctors_available': 'No doctors are currently available.',
  'yrs_experience': 'yrs experience',
  'free': 'Free',
  'per_consult': 'per consult',
  'pay_and_book': 'Pay and Book —',
  'choose_different_doctor': 'Choose a different doctor',
  'available_times_for': 'Available times for',
  'no_open_slots': 'This doctor has no open slots right now. Please check back later.',
  'describe_problem_for_doctor': 'Describe the problem (shared with the doctor)',
  'symptoms_hint_example': 'e.g. Fever and cough for 3 days…',
  'confirm_free_consultation': 'Confirm free consultation',
  'confirm_booking': 'Confirm Booking',
  'booking_failed': 'Could not book this appointment. Please try again.',
  'appointment_confirmed': 'Appointment confirmed!',
  'view_my_appointments': 'View My Appointments',
  'doctor': 'Doctor',
  'no_appointments_yet': 'No appointments yet. Book a consultation to get started.',
  'join_video_call': 'Join Video Call',
  'video_consultation': 'Video Consultation',
  'payment_verification_failed': 'Payment verification failed.',
  'payment_init_failed': 'Failed to initiate payment.',
  'payment_confirm_network_error': 'Could not confirm your payment due to a network error. If you were charged, it will be reconciled automatically — please check your booking status before paying again.',
  'payment_cancelled': 'Payment cancelled. You have not been charged.',
  'payment_failed': 'Payment failed. Please try again.',
};

const Map<String, String> _ta = {
  'app_title': 'கிராம்கேர் AI',
  'tagline': 'ஆஃப்லைன்-முதல் சுகாதார அமைப்பு',
  'back': 'பின் செல்',
  'medicine_recall_alert': 'மருந்து திரும்பப் பெறல் எச்சரிக்கை',
  'login': 'உள்நுழைக',
  'username_hint': 'பயனர்பெயர் (எ.கா. patient1)',
  'username_or_email_hint': 'பயனர்பெயர் அல்லது மின்னஞ்சல்',
  'password_hint': 'கடவுச்சொல்',
  'invalid_credentials': 'தவறான விவரங்கள். மீண்டும் முயற்சிக்கவும்.',
  'forgot_password': 'கடவுச்சொல் மறந்துவிட்டதா?',
  'new_patient_register': 'கிராம்கேருக்கு புதியவரா? கணக்கை உருவாக்க',
  'create_account_title': 'உங்கள் கணக்கை உருவாக்கவும்',
  'create_account_subtitle': 'நோயாளிகளுக்கு இலவசம் — ஒரு நிமிடத்திற்குள் முடியும்.',
  'full_name_hint': 'முழுப் பெயர்',
  'email_hint': 'மின்னஞ்சல்',
  'phone_hint_optional': 'தொலைபேசி (விருப்பம் — SMS நினைவூட்டல்களுக்கு)',
  'password_hint_min8': 'கடவுச்சொல் (குறைந்தது 8 எழுத்துகள்)',
  'create_account': 'கணக்கை உருவாக்கு',
  'already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக',
  'fill_required_fields': 'பெயர், பயனர்பெயர், மின்னஞ்சல் மற்றும் கடவுச்சொல்லை நிரப்பவும்.',
  'username_too_short': 'பயனர்பெயர் குறைந்தது 3 எழுத்துகள் இருக்க வேண்டும்.',
  'password_too_short': 'கடவுச்சொல் குறைந்தது 8 எழுத்துகள் இருக்க வேண்டும்.',
  'registration_failed': 'பதிவு தோல்வியடைந்தது. உங்கள் விவரங்களைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
  'reset_password_title': 'கடவுச்சொல்லை மீட்டமைக்க',
  'reset_password_tagline': 'உங்கள் கணக்கு மின்னஞ்சலை உள்ளிடவும், மீட்டமைப்பு இணைப்பை அனுப்புவோம்.',
  'send_reset_link': 'மீட்டமைப்பு இணைப்பை அனுப்பு',
  'reset_link_sent': 'அந்த மின்னஞ்சல் பதிவு செய்யப்பட்டிருந்தால், மீட்டமைப்பு இணைப்பை அனுப்பியுள்ளோம். உங்கள் இன்பாக்ஸைச் சரிபார்க்கவும்.',
  'reset_request_failed': 'மீட்டமைப்பு இணைப்பை அனுப்ப முடியவில்லை. இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
  'back_to_login': 'உள்நுழைவுக்குத் திரும்பு',
  'enter_valid_email': 'சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்.',
  'acting_for_self': 'யாருக்காக: நானே',
  'acting_for': 'யாருக்காக',
  'myself': 'நானே',
  'my_own_health': 'என் சொந்த ஆரோக்கியம்',
  'who_is_this_for': 'இது யாருக்காக?',
  'add_member': 'உறுப்பினரைச் சேர்க்க',
  'health_wallet': 'ஹெல்த் வாலட்',
  'symptom_checker': 'அறிகுறி பரிசோதனை',
  'scan_prescription': 'மருந்துச்சீட்டை ஸ்கேன்',
  'find_medicine': 'மருந்து தேடு',
  'iot_vitals': 'உடல்நிலை அளவீடுகள்',
  'medicine_reminders': 'மருந்து நினைவூட்டல்',
  'emergency_sos': 'அவசர உதவி (SOS)',
  'emergency_contacts': 'அவசர தொடர்புகள்',
  'hold_to_sos': 'SOS அனுப்ப பட்டனை 3 வினாடி அழுத்திப் பிடிக்கவும்',
  'hold_to_sos_listening': 'அழுத்திப் பிடித்து என்ன நடந்தது என்று சொல்லுங்கள்',
  'sos_sent': 'அவசர SOS அனுப்பப்பட்டது — உதவி வருகிறது',
  'sos_failed': 'SOS அனுப்ப முடியவில்லை. 108-ஐ நேரடியாக அழைக்கவும்.',
  'sos_sms_fallback': 'இணையம் இல்லை — உங்கள் தொடர்புகளுக்கு SMS அனுப்புகிறோம்',
  'sos_status_active': 'எச்சரிக்கை அனுப்பப்பட்டது — மருத்துவமனையின் பதிலுக்காக காத்திருக்கிறோம்.',
  'sos_status_responded': 'உதவி வருகிறது. உங்கள் எச்சரிக்கைக்கு ஒரு மருத்துவமனை பதிலளித்துள்ளது.',
  'sos_status_resolved': 'இந்த அவசரநிலை தீர்க்கப்பட்டதாகக் குறிக்கப்பட்டுள்ளது.',
  'sos_escalated': 'இன்னும் பதில் இல்லை — உங்கள் எச்சரிக்கை அடுத்த அருகிலுள்ள மருத்துவமனைக்கு அனுப்பப்பட்டுள்ளது.',
  'sos_status_error': 'உங்கள் எச்சரிக்கை நிலையைச் சரிபார்க்க முடியவில்லை. மீண்டும் முயற்சிக்கிறோம்…',
  'open_in_maps': 'வரைபடத்தில் திற',
  'describe_symptoms': 'உங்கள் அறிகுறிகளை விவரமாகச் சொல்லுங்கள்:',
  'speak_symptoms': 'மைக்கைத் தட்டி பேசுங்கள்',
  'add_symptom_photo': 'அறிகுறியின் புகைப்படத்தைச் சேர்க்கவும் (விருப்பத்திற்குரியது)',
  'listening': 'கேட்கிறது…',
  'analyze_with_ai': 'AI மூலம் பரிசோதிக்க',
  'analyzing': 'பரிசோதிக்கிறது…',
  'severity_score': 'தீவிர அளவு',
  'predicted_condition': 'சாத்தியமான பிரச்சனை',
  'doctor_recommendation': 'மருத்துவர் பரிந்துரை',
  'home_remedies': 'வீட்டு வைத்தியம்',
  'first_aid': 'முதலுதவி',
  'possible_causes': 'சாத்தியமான காரணங்கள்',
  'treatment_options': 'சிகிச்சை வழிகள்',
  'untreated_outcome': 'கவனிக்காவிட்டால்',
  'specialist': 'பரிந்துரைக்கப்படும் நிபுணர்',
  'recovery_time': 'குணமாகும் காலம்',
  'side_effects': 'கவனிக்க வேண்டிய பக்க விளைவுகள்',
  'why_ai_thinks_this': 'AI ஏன் இப்படி நினைக்கிறது?',
  'tap_to_hear': 'கேட்கத் தட்டவும்',
  'critical_prompt_title': 'இது தீவிரமாகத் தெரிகிறது',
  'critical_prompt_body': 'AI மதிப்பீடு மிக அவசரம் என்கிறது. இப்போதே அவசர SOS அனுப்பவா?',
  'send_sos_now': 'இப்போதே SOS அனுப்பு',
  'not_now': 'இப்போது வேண்டாம்',
  'no_records': 'இன்னும் பதிவுகள் இல்லை. அறிகுறி பரிசோதனை அல்லது ஸ்கேன் செய்யுங்கள்.',
  'sync_now': 'இப்போது ஒத்திசை',
  'save_to_wallet': 'சரியாக உள்ளது — வாலட்டில் சேமிக்க',
  'retake_photo': 'மீண்டும் புகைப்படம் எடு',
  'saved_to_wallet': 'ஹெல்த் வாலட்டில் சேமிக்கப்பட்டது — இணையம் வந்ததும் ஒத்திசையும்',
  'camera': 'கேமரா',
  'gallery': 'கேலரி',
  'search_failed': 'தேடல் தோல்வி. இணையம் உள்ளதா?',
  'offline_estimate_banner': 'ஆஃப்லைன் மதிப்பீடு — முழுமையான AI பகுப்பாய்வு அல்ல. சர்வரை அடைய முடியாததால் இது ஒரு அடிப்படை கீவேர்ட் அடிப்படையிலான பாதுகாப்பு சோதனை மட்டுமே. முடிந்தவுடன் இணையத்துடன் இணையவும், இது தீவிரமாக உணரப்பட்டால் உடனடியாக மருத்துவ உதவியை நாடவும்.',
  'offline_no_match': 'நீங்கள் ஆஃப்லைனில் இருப்பதாகத் தெரிகிறது, மேலும் இந்த அறிகுறிகளுக்கு ஆஃப்லைன் மதிப்பீடு கூட வழங்க முடியவில்லை. கவலையாக இருந்தால், தயவுசெய்து மருத்துவ உதவியை நாடவும் அல்லது உங்கள் உள்ளூர் அவசர எண்ணை அழைக்கவும்.',
  'in_stock': 'இருப்பில் உள்ளது',
  'not_available': 'இங்கு கிடைக்கவில்லை',
  'alternatives': 'அதே பலன் தரும் மாற்று மருந்துகள்',
  'language': 'மொழி',
  'name': 'பெயர்',
  'phone': 'தொலைபேசி',
  'relation': 'உறவு',
  'save': 'சேமிக்க',
  // Health Passport
  'health_passport': 'சுகாதார பாஸ்போர்ட்',
  // Lab tests
  'lab_tests': 'ஆய்வக பரிசோதனைகள்',
  // Preventive care & referrals
  'preventive_care': 'தடுப்பு பராமரிப்பு',
  // My Care (AI Care Navigator)
  'my_care': 'என் பராமரிப்பு',
  'my_care_subtitle': 'அடுத்து என்ன செய்ய வேண்டும், முக்கியத்துவ வரிசையில் — ஒவ்வொன்றுக்கும் காரணத்துடன்.',
  'my_care_none': 'இப்போது உங்கள் கவனம் தேவைப்படுவது எதுவும் இல்லை.',
  'my_care_load_failed': 'உங்கள் பராமரிப்புத் திட்டத்தை ஏற்ற முடியவில்லை.',
  'open': 'திற',
  'priority_critical': 'மிக அவசரம்',
  'priority_high': 'அதிகம்',
  'priority_medium': 'நடுத்தரம்',
  'priority_low': 'குறைவு',
  'preventive_due_tab': 'இப்போது தேவை',
  'referrals_tab': 'பரிந்துரைகள்',
  'preventive_none': 'இதுவரை தடுப்பு பரிசோதனைகள் பரிந்துரைக்கப்படவில்லை.',
  'preventive_due_now': 'கவனம் தேவை',
  'preventive_up_to_date': 'தற்போதைய நிலையில் உள்ளது',
  'preventive_due_badge': 'தேவை',
  'preventive_last_done': 'கடைசியாக செய்தது',
  'preventive_book_test': 'இந்த பரிசோதனையை பதிவு செய்யவும்',
  'preventive_book_consult': 'ஆலோசனையை பதிவு செய்யவும்',
  'preventive_load_failed': 'உங்கள் தடுப்பு பராமரிப்பு பரிசோதனைகளை ஏற்ற முடியவில்லை.',
  'referrals_load_failed': 'உங்கள் பரிந்துரைகளை ஏற்ற முடியவில்லை.',
  'referrals_none': 'இதுவரை பரிந்துரைகள் இல்லை. மருத்துவர் உங்களை நிபுணருக்கு பரிந்துரைக்கலாம்.',
  'referral_status_pending': 'நிலுவையில்',
  'referral_status_accepted': 'ஏற்கப்பட்டது',
  'referral_status_declined': 'நிராகரிக்கப்பட்டது',
  'referral_status_completed': 'முடிந்தது',
  'lab_book_tab': 'பரிசோதனை பதிவு',
  'lab_my_bookings_tab': 'என் பதிவுகள்',
  'lab_search_hint': 'பரிசோதனைகளைத் தேடுங்கள் (இரத்த சர்க்கரை, தைராய்டு...)',
  'lab_no_tests': 'உங்கள் தேடலுக்கு பரிசோதனைகள் இல்லை.',
  'lab_no_bookings': 'இதுவரை ஆய்வக பரிசோதனைகள் பதிவு செய்யப்படவில்லை.',
  'lab_choose_center': 'ஆய்வக மையத்தைத் தேர்ந்தெடுக்கவும்',
  'lab_home_collection': 'என் வீட்டிலேயே மாதிரியை சேகரிக்கவும்',
  'lab_confirm_booking': 'பதிவை உறுதிப்படுத்தவும்',
  'lab_booked': 'பரிசோதனை பதிவு செய்யப்பட்டது. ஆய்வகம் நிலையைப் புதுப்பிக்கும்.',
  'lab_booking_failed': 'இந்த பரிசோதனையை பதிவு செய்ய முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  'lab_tests_load_failed': 'பரிசோதனை பட்டியலை ஏற்ற முடியவில்லை.',
  'lab_bookings_load_failed': 'உங்கள் பதிவுகளை ஏற்ற முடியவில்லை.',
  'lab_centers_load_failed': 'ஆய்வக மையங்களை ஏற்ற முடியவில்லை.',
  'lab_no_centers': 'இதுவரை ஆய்வக மையங்கள் எதுவும் இல்லை.',
  'lab_report': 'அறிக்கை',
  'lab_status_booked': 'பதிவு செய்யப்பட்டது',
  'lab_status_sample_collected': 'மாதிரி சேகரிக்கப்பட்டது',
  'lab_status_processing': 'செயலாக்கத்தில்',
  'lab_status_report_ready': 'அறிக்கை தயார்',
  'lab_status_completed': 'முடிந்தது',
  'lab_status_cancelled': 'ரத்து செய்யப்பட்டது',
  'passport_subtitle': 'கிராம்கேர் கணக்கு இல்லாமலேயே துணை மருத்துவர் அல்லது மருத்துவமனை உங்கள் தொலைபேசியில் படிக்கக்கூடிய அவசர விவரங்கள்.',
  'blood_group': 'இரத்த வகை',
  'allergies': 'ஒவ்வாமைகள்',
  'allergies_hint': 'எ.கா. பெனிசிலின், நிலக்கடலை',
  'chronic_conditions': 'நாள்பட்ட நோய்கள்',
  'chronic_conditions_hint': 'எ.கா. வகை 2 நீரிழிவு, ஆஸ்துமா',
  'saving': 'சேமிக்கிறது...',
  'passport_load_failed': 'உங்கள் சுகாதார பாஸ்போர்ட்டை ஏற்ற முடியவில்லை.',
  'passport_saved': 'சுகாதார பாஸ்போர்ட் சேமிக்கப்பட்டது.',
  'passport_save_failed': 'உங்கள் சுகாதார பாஸ்போர்ட்டை சேமிக்க முடியவில்லை.',
  'passport_qr_note': 'அவசரநிலையில் இந்தக் குறியீட்டைக் காட்டுங்கள். ஸ்கேன் செய்தால் உங்கள் இரத்த வகை, ஒவ்வாமைகள், நோய்கள் தெரியும் — உள்நுழைவு தேவையில்லை.',
  'passport_copy_link': 'இணைப்பை நகலெடு',
  'passport_link_copied': 'இணைப்பு நகலெடுக்கப்பட்டது.',
  'passport_new_code': 'புதிய குறியீடு',
  'passport_regenerate_confirm': 'புதிய QR குறியீட்டை உருவாக்கவா? பழையது செயலிழக்கும் — உங்கள் தொலைபேசி அல்லது அச்சிட்ட நகல் தொலைந்தால் இதைப் பயன்படுத்தவும்.',
  'passport_new_code_done': 'புதிய QR குறியீடு உருவாக்கப்பட்டது. பழையது இனி வேலை செய்யாது.',
  'passport_regenerate_failed': 'புதிய QR குறியீட்டை உருவாக்க முடியவில்லை.',
  'passport_save_for_qr': 'அவசர QR குறியீட்டை உருவாக்க உங்கள் விவரங்களைச் சேமிக்கவும்.',
  'cancel': 'ரத்து',
  'delete': 'நீக்கு',
  'add_contact': 'தொடர்பைச் சேர்க்க',
  'no_contacts': 'அவசர நேரத்தில் அறிவிக்க குடும்ப எண்களைச் சேர்க்கவும்.',
  'offline_note': 'ஆஃப்லைன் — இணையம் வந்ததும் ஒத்திசையும்',
  'add_family_member_title': 'குடும்ப உறுப்பினரைச் சேர்க்க',
  'relation_hint': 'உறவு (எ.கா. அம்மா)',
  'age_hint': 'வயது',
  'gender_female': 'பெண்',
  'gender_male': 'ஆண்',
  'gender_other': 'மற்றவை',
  'could_not_save_member': 'உறுப்பினரைச் சேமிக்க முடியவில்லை. இணையத்தில் உள்ளீர்களா?',
  'medicine_name_hint': 'மருந்தின் பெயர் (எ.கா. பாராசிட்டமால்)',
  'search_medicine_prompt': 'உங்கள் மருந்து எந்த மருந்தகத்தில் உள்ளது எனத் தேடுங்கள்.',
  'no_pharmacies_found': 'மருந்தகங்கள் எதுவும் இல்லை.',
  'jan_aushadhi': 'ஜன் ஔஷதி',
  'preorder_cta': 'மீண்டும் இருப்பு வரும்போது முன்பதிவு',
  'preordered_notify': 'முன்பதிவு செய்யப்பட்டது — நாங்கள் அறிவிப்போம்',
  'preorder_failed': 'முன்பதிவு செய்ய முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  'health_vitals_title': 'உடல்நல அளவீடுகள்',
  'heart_rate': 'இதயத் துடிப்பு',
  'spo2': 'SpO2',
  'sleep_deep': 'தூக்கம் (ஆழமான)',
  'sleep_light': 'தூக்கம் (இலேசான)',
  'steps_today': 'அடிகள் இன்று',
  'daily_step_goal': 'தினசரி அடி இலக்கு',
  'heart_rate_trend': 'இதயத் துடிப்பு போக்கு (bpm)',
  'spo2_trend': 'SpO2 போக்கு (%)',
  'no_data_yet': 'இன்னும் தரவு இல்லை',
  'sync_or_log_manually': 'ஒரு சாதனத்தை இணைக்கவும், அல்லது அளவீடுகளை நீங்களே உள்ளிடவும்:',
  'heart_rate_bpm': 'இதயத் துடிப்பு (bpm)',
  'spo2_percent': 'SpO2 (%)',
  'steps_today_label': 'இன்றைய அடிகள்',
  'deep_sleep_hrs': 'ஆழமான தூக்கம் (மணிநேரம்)',
  'light_sleep_hrs': 'இலேசான தூக்கம் (மணிநேரம்)',
  'save_vitals': 'அளவீடுகளைச் சேமிக்க',
  'invalid_vitals_range': 'மதிப்புகளைச் சரிபார்க்கவும்: இதயத் துடிப்பு 1–299, SpO2 0–100, வெப்பநிலை 25–45 °C.',
  'ai_limit_exhausted': 'AI வரம்பு முடிந்தது',
  'have_own_api_key': 'உங்களிடம் சொந்த API விசை உள்ளதா?',
  'yes': 'ஆம்',
  'no': 'இல்லை',
  'paste_api_key': 'உங்கள் API விசையை ஒட்டவும்',
  'api_key_stays_on_phone': 'இந்த தொலைபேசியில் மட்டுமே சேமிக்கப்படும். GramCare-க்கு அனுப்பப்படாது.',
  'save_and_retry': 'சேமித்து மீண்டும் முயற்சி',
  'ai_using_your_key': 'உங்கள் API விசை பயன்படுத்தப்படுகிறது',
  'remove_api_key': 'விசையை நீக்கு',
  'vitals_saved': 'அளவீடுகள் வெற்றிகரமாகப் பதிவு செய்யப்பட்டன.',
  'vitals_save_failed': 'அளவீடுகளைச் சேமிக்க முடியவில்லை. இணையத்தில் உள்ளீர்களா?',
  'connect_ble_device': 'புளூடூத் சுகாதார சாதனத்தை இணைக்கவும்',
  'ble_profiles_note': 'நிலையான புளூடூத் இதயத் துடிப்பு, பல்ஸ் ஆக்சிமீட்டர் அல்லது வெப்பமானி சுயவிவரத்தை ஆதரிக்கும் சாதனங்களுடன் செயல்படும்.',
  'ble_not_supported': 'இந்தத் தொலைபேசி புளூடூத் லோ எனர்ஜியை ஆதரிக்கவில்லை.',
  'ble_turn_on': 'சாதனத்தை இணைக்க புளூடூத்தை இயக்கவும்.',
  'ble_choose_device': 'ஒரு சாதனத்தைத் தேர்ந்தெடுக்கவும்',
  'ble_searching': 'சுகாதார சாதனங்களைத் தேடுகிறது…',
  'ble_none_found': 'சுகாதார சாதனங்கள் எதுவும் கிடைக்கவில்லை. சாதனம் இயக்கத்தில் உள்ளதா, அருகில் உள்ளதா எனச் சரிபார்க்கவும்.',
  'ble_scan_failed': 'சாதனங்களைத் தேட முடியவில்லை. புளூடூத் அனுமதியைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
  'ble_unnamed_device': 'பெயரிடப்படாத சாதனம்',
  'ble_connecting': 'இணைக்கிறது…',
  'ble_connect_failed': 'சாதனத்துடன் இணைக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  'ble_no_health_data': 'இந்தச் சாதனம் நிலையான சுகாதார அளவீடுகளை வழங்கவில்லை.',
  'ble_live_from': 'நேரடி அளவீடுகள்:',
  'ble_waiting_reading': 'அளவீட்டிற்காகக் காத்திருக்கிறது — சாதனத்தை உங்கள் விரலில் அல்லது தோலில் வைத்திருக்கவும்.',
  'ble_disconnect': 'துண்டிக்கவும்',
  'ble_disconnected': 'சாதனம் துண்டிக்கப்பட்டது.',
  'ble_search_again': 'மீண்டும் தேடவும்',
  'temperature': 'உடல் வெப்பநிலை',
  'temperature_c': 'உடல் வெப்பநிலை (°C)',
  'sleep_deep_light': 'தூக்கம் (ஆழமான / இலேசான)',
  'vitals_need_one_value': 'குறைந்தது ஒரு அளவீட்டை உள்ளிடவும்.',
  'camera_open_failed': 'கேமரா/கேலரியைத் திறக்க முடியவில்லை.',
  'ocr_read_failed': 'மருந்துச்சீட்டைப் படிக்க முடியவில்லை. இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
  'scan_for': 'இதற்காக ஸ்கேன்:',
  'ai_reading_prescription': 'AI மருந்துச்சீட்டைப் படிக்கிறது…',
  'ai_found_medicines': 'AI கண்டறிந்த மருந்துகள்:',
  'sure': 'உறுதி',
  'no_medicines_recognized': 'மருந்துகள் எதுவும் கண்டறியப்படவில்லை — புகைப்பட தரத்தைச் சரிபார்க்கவும்.',
  'full_text': 'முழு உரை:',
  'medicine_info_failed': 'மருந்து தகவலை ஏற்ற முடியவில்லை. இணையத்தில் உள்ளீர்களா?',
  'what_its_for': 'இது எதற்காக',
  'dosage_guidance': 'மருந்து அளவு வழிகாட்டுதல்',
  'side_effects_watch': 'கவனிக்க வேண்டிய பக்க விளைவுகள்',
  'precautions': 'முன்னெச்சரிக்கைகள்',
  'book_consultation': 'ஆலோசனை பதிவு',
  'my_appointments': 'எனது அப்பாயின்ட்மென்ட்கள்',
  'no_doctors_available': 'தற்போது மருத்துவர்கள் யாரும் கிடைக்கவில்லை.',
  'yrs_experience': 'ஆண்டுகள் அனுபவம்',
  'free': 'இலவசம்',
  'per_consult': 'ஆலோசனைக்கு',
  'pay_and_book': 'செலுத்தி பதிவு செய் —',
  'choose_different_doctor': 'வேறு மருத்துவரைத் தேர்வு செய்க',
  'available_times_for': 'கிடைக்கும் நேரங்கள் — ',
  'no_open_slots': 'இந்த மருத்துவருக்கு தற்போது திறந்த நேரங்கள் இல்லை. பின்னர் மீண்டும் பாருங்கள்.',
  'describe_problem_for_doctor': 'பிரச்சனையை விவரிக்கவும் (மருத்துவருடன் பகிரப்படும்)',
  'symptoms_hint_example': 'எ.கா. 3 நாட்களாக காய்ச்சல் மற்றும் இருமல்…',
  'confirm_free_consultation': 'இலவச ஆலோசனையை உறுதிப்படுத்து',
  'confirm_booking': 'பதிவை உறுதிப்படுத்து',
  'booking_failed': 'இந்த அப்பாயின்ட்மென்ட்டை பதிவு செய்ய முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  'appointment_confirmed': 'அப்பாயின்ட்மென்ட் உறுதி செய்யப்பட்டது!',
  'view_my_appointments': 'எனது அப்பாயின்ட்மென்ட்களைப் பார்க்க',
  'doctor': 'மருத்துவர்',
  'no_appointments_yet': 'இன்னும் அப்பாயின்ட்மென்ட்கள் இல்லை. ஆலோசனை பதிவு செய்யத் தொடங்குங்கள்.',
  'join_video_call': 'வீடியோ அழைப்பில் சேர',
  'video_consultation': 'வீடியோ ஆலோசனை',
  'payment_verification_failed': 'கட்டணச் சரிபார்ப்பு தோல்வியடைந்தது.',
  'payment_init_failed': 'கட்டணத்தைத் தொடங்க முடியவில்லை.',
  'payment_confirm_network_error': 'நெட்வொர்க் பிழையால் உங்கள் கட்டணத்தை உறுதிப்படுத்த முடியவில்லை. நீங்கள் கட்டணம் செலுத்தியிருந்தால், அது தானாக சரிசெய்யப்படும் — மீண்டும் செலுத்தும் முன் உங்கள் பதிவு நிலையைச் சரிபார்க்கவும்.',
  'payment_cancelled': 'கட்டணம் ரத்து செய்யப்பட்டது. உங்களிடமிருந்து பணம் வசூலிக்கப்படவில்லை.',
  'payment_failed': 'கட்டணம் தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.',
};
