// GENERATED CODE - DO NOT MODIFY BY HAND
// (Regenerated by hand to match the extended model; field-count tolerant so
// records written by the previous 4-field version still deserialize.)

part of 'health_record.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class HealthRecordAdapter extends TypeAdapter<HealthRecord> {
  @override
  final int typeId = 0;

  @override
  HealthRecord read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return HealthRecord(
      patientName: fields[0] as String,
      symptoms: fields[1] as String,
      aiSeverity: fields[2] as String,
      timestamp: fields[3] as DateTime,
      recordType: fields[4] as String? ?? 'note',
      title: fields[5] as String?,
      familyProfileId: fields[6] as int?,
      doctorName: fields[7] as String?,
      clientUuid: fields[8] as String?,
      synced: fields[9] as bool? ?? false,
    );
  }

  @override
  void write(BinaryWriter writer, HealthRecord obj) {
    writer
      ..writeByte(10)
      ..writeByte(0)
      ..write(obj.patientName)
      ..writeByte(1)
      ..write(obj.symptoms)
      ..writeByte(2)
      ..write(obj.aiSeverity)
      ..writeByte(3)
      ..write(obj.timestamp)
      ..writeByte(4)
      ..write(obj.recordType)
      ..writeByte(5)
      ..write(obj.title)
      ..writeByte(6)
      ..write(obj.familyProfileId)
      ..writeByte(7)
      ..write(obj.doctorName)
      ..writeByte(8)
      ..write(obj.clientUuid)
      ..writeByte(9)
      ..write(obj.synced);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HealthRecordAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
