"""Initial migration

Revision ID: 34cdce76363d
Revises: 
Create Date: 2026-06-29 20:39:18.874858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34cdce76363d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ehr_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('record_type', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('doctor_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ehr_records_id'), 'ehr_records', ['id'], unique=False)
    op.create_index(op.f('ix_ehr_records_patient_id'), 'ehr_records', ['patient_id'], unique=False)
    op.create_table('pharmacy_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.String(), nullable=True),
    sa.Column('medicine_name', sa.String(), nullable=True),
    sa.Column('stock_count', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('requires_prescription', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacy_inventory_id'), 'pharmacy_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_medicine_name'), 'pharmacy_inventory', ['medicine_name'], unique=False)
    op.create_index(op.f('ix_pharmacy_inventory_pharmacy_id'), 'pharmacy_inventory', ['pharmacy_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pharmacy_inventory_pharmacy_id'), table_name='pharmacy_inventory')
    op.drop_index(op.f('ix_pharmacy_inventory_medicine_name'), table_name='pharmacy_inventory')
    op.drop_index(op.f('ix_pharmacy_inventory_id'), table_name='pharmacy_inventory')
    op.drop_table('pharmacy_inventory')
    op.drop_index(op.f('ix_ehr_records_patient_id'), table_name='ehr_records')
    op.drop_index(op.f('ix_ehr_records_id'), table_name='ehr_records')
    op.drop_table('ehr_records')
    # ### end Alembic commands ###
