"""Add cloudinary url fields

Revision ID: 60b438953732
Revises: 57ce2514a3f6
Create Date: 2026-07-08 10:19:19.842610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60b438953732'
down_revision: Union[str, Sequence[str], None] = '57ce2514a3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_recalls', sa.Column('notice_url', sa.String(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('photo_url', sa.String(), nullable=True))
    op.drop_index(op.f('ix_payments_patient_idempotency_unique'), table_name='payments', postgresql_where='(idempotency_key IS NOT NULL)')
    op.add_column('triage_logs', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_index(op.f('ix_user_push_tokens_fcm_token'), table_name='user_push_tokens', postgresql_where='(is_active IS TRUE)')
    op.create_index(op.f('ix_user_push_tokens_fcm_token'), 'user_push_tokens', ['fcm_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_push_tokens_fcm_token'), table_name='user_push_tokens')
    op.create_index(op.f('ix_user_push_tokens_fcm_token'), 'user_push_tokens', ['fcm_token'], unique=True, postgresql_where='(is_active IS TRUE)')
    op.drop_column('triage_logs', 'image_url')
    op.create_index(op.f('ix_payments_patient_idempotency_unique'), 'payments', ['patient_id', 'idempotency_key'], unique=True, postgresql_where='(idempotency_key IS NOT NULL)')
    op.drop_column('doctor_profiles', 'photo_url')
    op.drop_column('batch_recalls', 'notice_url')
    # ### end Alembic commands ###
