"""add user_push_tokens

Revision ID: 8757c24a7b38
Revises: a1b2c3d4e5f6
Create Date: 2026-07-04 17:10:26.756727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8757c24a7b38'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_push_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('fcm_token', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE (manually adjusted, not autogenerated): fcm_token is unique only
    # among ACTIVE rows, not globally. The FCM-token registration endpoint
    # deactivates (is_active=False) another user's row for the same physical
    # device token instead of deleting it, so the same token value legitimately
    # exists on more than one row (e.g. a shared clinic tablet where a
    # different staff member logs in later) — a plain unique index would
    # reject that second INSERT with an IntegrityError. A partial unique index
    # enforces "at most one active owner per token" while still allowing
    # historical inactive duplicates.
    op.create_index(
        op.f('ix_user_push_tokens_fcm_token'), 'user_push_tokens', ['fcm_token'],
        unique=True,
        sqlite_where=sa.text('is_active'),
        postgresql_where=sa.text('is_active IS TRUE'),
    )
    op.create_index(op.f('ix_user_push_tokens_id'), 'user_push_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_user_push_tokens_user_id'), 'user_push_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    # NOTE (manually adjusted, not autogenerated): SQLite has no ALTER TABLE
    # support for dropping/adding constraints — op.drop_constraint() raises
    # NotImplementedError against it (this migration previously only worked
    # against Postgres; the test suite runs the whole chain on SQLite, so it
    # would crash on `alembic upgrade head` there). batch_alter_table wraps
    # each change in SQLite's documented
    # copy-and-move strategy, and is a no-op passthrough to a plain ALTER on
    # dialects that support it directly (Postgres), so this is safe either way.
    #
    # A second SQLite-specific wrinkle: these four constraints were originally
    # created via a bare `Column(unique=True)` (Postgres auto-names that
    # `<table>_<column>_key`). SQLite implements column-level `unique=True` as
    # an implicit, unnamed autoindex rather than a named table CONSTRAINT, so
    # batch mode's reflection never finds a constraint called e.g.
    # `doctor_profiles_user_id_key` to drop and raises
    # `ValueError: No such constraint`. There is nothing to drop by name on
    # SQLite in that case — the explicit `ix_*_user_id` unique index created
    # right after supersedes it functionally — so the drop is skipped there
    # and only performed on dialects (Postgres) where it's a real named
    # constraint.
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'
    if not is_sqlite:
        with op.batch_alter_table('doctor_profiles') as batch_op:
            batch_op.drop_constraint(op.f('doctor_profiles_user_id_key'), type_='unique')
    op.create_index(op.f('ix_doctor_profiles_user_id'), 'doctor_profiles', ['user_id'], unique=True)
    if not is_sqlite:
        with op.batch_alter_table('ehr_records') as batch_op:
            batch_op.drop_constraint(op.f('ehr_records_client_uuid_key'), type_='unique')
    op.drop_index(op.f('ix_ehr_records_client_uuid'), table_name='ehr_records')
    op.create_index(op.f('ix_ehr_records_client_uuid'), 'ehr_records', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_family_profiles_user_id'), 'family_profiles', ['user_id'], unique=False)
    if not is_sqlite:
        with op.batch_alter_table('payments') as batch_op:
            batch_op.drop_constraint(op.f('payments_order_id_key'), type_='unique')
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.create_index(op.f('ix_payments_patient_id'), 'payments', ['patient_id'], unique=False)
    if not is_sqlite:
        with op.batch_alter_table('pharmacies') as batch_op:
            batch_op.drop_constraint(op.f('pharmacies_owner_user_id_key'), type_='unique')
    op.create_index(op.f('ix_pharmacies_owner_user_id'), 'pharmacies', ['owner_user_id'], unique=True)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_pharmacies_owner_user_id'), table_name='pharmacies')
    # Same SQLite batch-mode requirement as upgrade() — adding a unique
    # constraint via plain ALTER TABLE isn't supported by SQLite either.
    with op.batch_alter_table('pharmacies') as batch_op:
        batch_op.create_unique_constraint(op.f('pharmacies_owner_user_id_key'), ['owner_user_id'])
    op.drop_index(op.f('ix_payments_patient_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    with op.batch_alter_table('payments') as batch_op:
        batch_op.create_unique_constraint(op.f('payments_order_id_key'), ['order_id'])
    op.drop_index(op.f('ix_family_profiles_user_id'), table_name='family_profiles')
    op.drop_index(op.f('ix_ehr_records_client_uuid'), table_name='ehr_records')
    op.create_index(op.f('ix_ehr_records_client_uuid'), 'ehr_records', ['client_uuid'], unique=False)
    with op.batch_alter_table('ehr_records') as batch_op:
        batch_op.create_unique_constraint(op.f('ehr_records_client_uuid_key'), ['client_uuid'])
    op.drop_index(op.f('ix_doctor_profiles_user_id'), table_name='doctor_profiles')
    with op.batch_alter_table('doctor_profiles') as batch_op:
        batch_op.create_unique_constraint(op.f('doctor_profiles_user_id_key'), ['user_id'])
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_user_push_tokens_user_id'), table_name='user_push_tokens')
    op.drop_index(op.f('ix_user_push_tokens_id'), table_name='user_push_tokens')
    op.drop_index(op.f('ix_user_push_tokens_fcm_token'), table_name='user_push_tokens')
    op.drop_table('user_push_tokens')
    # ### end Alembic commands ###
