"""add jan aushadhi flag, batch recalls, medicine preorders

Revision ID: af17308dc16e
Revises: c2f4a9d1e6b7
Create Date: 2026-07-06 21:16:38.207121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af17308dc16e'
down_revision: Union[str, Sequence[str], None] = 'c2f4a9d1e6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_recalls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('issued_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_recalls_batch_number'), 'batch_recalls', ['batch_number'], unique=False)
    op.create_index(op.f('ix_batch_recalls_id'), 'batch_recalls', ['id'], unique=False)
    op.create_index(op.f('ix_batch_recalls_medicine_name'), 'batch_recalls', ['medicine_name'], unique=False)
    op.create_table('medicine_preorders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.Column('medicine_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_preorders_id'), 'medicine_preorders', ['id'], unique=False)
    op.create_index(op.f('ix_medicine_preorders_patient_id'), 'medicine_preorders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medicine_preorders_pharmacy_id'), 'medicine_preorders', ['pharmacy_id'], unique=False)
    op.add_column('pharmacies', sa.Column('is_jan_aushadhi', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed touching ix_payments_patient_idempotency_unique
    # and ix_user_push_tokens_fcm_token. That's pre-existing drift between the
    # models and prior migrations caused by how SQLite reflects partial/unique
    # indexes (sqlite_where) — unrelated to this migration's scope, so it is
    # deliberately left untouched here rather than silently rewritten.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacies', 'is_jan_aushadhi')
    op.drop_index(op.f('ix_medicine_preorders_pharmacy_id'), table_name='medicine_preorders')
    op.drop_index(op.f('ix_medicine_preorders_patient_id'), table_name='medicine_preorders')
    op.drop_index(op.f('ix_medicine_preorders_id'), table_name='medicine_preorders')
    op.drop_table('medicine_preorders')
    op.drop_index(op.f('ix_batch_recalls_medicine_name'), table_name='batch_recalls')
    op.drop_index(op.f('ix_batch_recalls_id'), table_name='batch_recalls')
    op.drop_index(op.f('ix_batch_recalls_batch_number'), table_name='batch_recalls')
    op.drop_table('batch_recalls')
    # ### end Alembic commands ###
