"""add steps and sleep fields to iot vitals

Revision ID: 57ce2514a3f6
Revises: da99b0dfe596
Create Date: 2026-07-07 16:45:29.723137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ce2514a3f6'
down_revision: Union[str, Sequence[str], None] = 'da99b0dfe596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iot_vitals', sa.Column('steps', sa.Integer(), nullable=True))
    op.add_column('iot_vitals', sa.Column('sleep_deep_hours', sa.Float(), nullable=True))
    op.add_column('iot_vitals', sa.Column('sleep_light_hours', sa.Float(), nullable=True))
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed touching ix_payments_patient_idempotency_unique
    # and ix_user_push_tokens_fcm_token — pre-existing drift from how SQLite
    # reflects partial/unique indexes (sqlite_where), unrelated to this
    # migration; deliberately left untouched (see af17308dc16e for the same note).


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iot_vitals', 'sleep_light_hours')
    op.drop_column('iot_vitals', 'sleep_deep_hours')
    op.drop_column('iot_vitals', 'steps')
    # ### end Alembic commands ###
