"""add laboratory module

Revision ID: 59168084b57e
Revises: af17308dc16e
Create Date: 2026-07-06 21:51:04.797410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59168084b57e'
down_revision: Union[str, Sequence[str], None] = 'af17308dc16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('offers_home_collection', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_centers_id'), 'lab_centers', ['id'], unique=False)
    op.create_index(op.f('ix_lab_centers_lat'), 'lab_centers', ['lat'], unique=False)
    op.create_index(op.f('ix_lab_centers_lng'), 'lab_centers', ['lng'], unique=False)
    op.create_index(op.f('ix_lab_centers_owner_user_id'), 'lab_centers', ['owner_user_id'], unique=True)
    op.create_table('lab_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('family_profile_id', sa.Integer(), nullable=True),
    sa.Column('lab_center_id', sa.Integer(), nullable=True),
    sa.Column('test_name', sa.String(), nullable=True),
    sa.Column('home_collection', sa.Boolean(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('report_payload', sa.JSON(), nullable=True),
    sa.Column('report_ready_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_profile_id'], ['family_profiles.id'], ),
    sa.ForeignKeyConstraint(['lab_center_id'], ['lab_centers.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_bookings_id'), 'lab_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_lab_bookings_lab_center_id'), 'lab_bookings', ['lab_center_id'], unique=False)
    op.create_index(op.f('ix_lab_bookings_patient_id'), 'lab_bookings', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lab_bookings_status'), 'lab_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_lab_bookings_test_name'), 'lab_bookings', ['test_name'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed touching ix_payments_patient_idempotency_unique
    # and ix_user_push_tokens_fcm_token — pre-existing drift from how SQLite
    # reflects partial/unique indexes (sqlite_where), unrelated to this
    # migration; deliberately left untouched (see af17308dc16e for the same note).


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_bookings_test_name'), table_name='lab_bookings')
    op.drop_index(op.f('ix_lab_bookings_status'), table_name='lab_bookings')
    op.drop_index(op.f('ix_lab_bookings_patient_id'), table_name='lab_bookings')
    op.drop_index(op.f('ix_lab_bookings_lab_center_id'), table_name='lab_bookings')
    op.drop_index(op.f('ix_lab_bookings_id'), table_name='lab_bookings')
    op.drop_table('lab_bookings')
    op.drop_index(op.f('ix_lab_centers_owner_user_id'), table_name='lab_centers')
    op.drop_index(op.f('ix_lab_centers_lng'), table_name='lab_centers')
    op.drop_index(op.f('ix_lab_centers_lat'), table_name='lab_centers')
    op.drop_index(op.f('ix_lab_centers_id'), table_name='lab_centers')
    op.drop_table('lab_centers')
    # ### end Alembic commands ###
