"""add appointment triage severity score

Revision ID: da99b0dfe596
Revises: 59168084b57e
Create Date: 2026-07-07 16:14:38.085904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da99b0dfe596'
down_revision: Union[str, Sequence[str], None] = '59168084b57e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('triage_severity_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed touching ix_payments_patient_idempotency_unique
    # and ix_user_push_tokens_fcm_token — pre-existing drift from how SQLite
    # reflects partial/unique indexes (sqlite_where), unrelated to this
    # migration; deliberately left untouched (see af17308dc16e for the same note).


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'triage_severity_score')
    # ### end Alembic commands ###
